//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageServer.Web.Common.WebControls.Validators {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageServer.Web.Common.WebControls.Validators.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AE Title cannot be empty 的本地化字符串。
        /// </summary>
        public static string AETitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("AETitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AE Title &apos;{0}&apos; is already in use 的本地化字符串。
        /// </summary>
        public static string AETitleIsInUse {
            get {
                return ResourceManager.GetString("AETitleIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filesystem path cannot be empty 的本地化字符串。
        /// </summary>
        public static string FilesystemPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("FilesystemPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is either invalid or not reachable. 的本地化字符串。
        /// </summary>
        public static string FilesystemPathInvalidOrUnreachable {
            get {
                return ResourceManager.GetString("FilesystemPathInvalidOrUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is not a invalid number for {0} 的本地化字符串。
        /// </summary>
        public static string IsNotAValidNumber {
            get {
                return ResourceManager.GetString("IsNotAValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Folder cannot be empty 的本地化字符串。
        /// </summary>
        public static string PartitionFolderCannotBeEmpty {
            get {
                return ResourceManager.GetString("PartitionFolderCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Folder &apos;{0}&apos; is already in use 的本地化字符串。
        /// </summary>
        public static string PartitionFolderIsInUse {
            get {
                return ResourceManager.GetString("PartitionFolderIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Rule XML must be specified 的本地化字符串。
        /// </summary>
        public static string ServerRuleXMLIsMissing {
            get {
                return ResourceManager.GetString("ServerRuleXMLIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse rule : {0} 的本地化字符串。
        /// </summary>
        public static string UnableToParseServerRuleXML {
            get {
                return ResourceManager.GetString("UnableToParseServerRuleXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot validate path {0}: {1} 的本地化字符串。
        /// </summary>
        public static string UnableToValidatePath {
            get {
                return ResourceManager.GetString("UnableToValidatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usergroup &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string UserGroupAlreadyExists {
            get {
                return ResourceManager.GetString("UserGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usergroup name cannot be empty 的本地化字符串。
        /// </summary>
        public static string UserGroupCannotBeEmpty {
            get {
                return ResourceManager.GetString("UserGroupCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username cannot be empty 的本地化字符串。
        /// </summary>
        public static string UsernameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UsernameCannotBeEmpty", resourceCulture);
            }
        }
    }
}
