//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.Enterprise.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.Enterprise.Core.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The operation could not complete because it was deadlocked with another operation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDeadlockDetected {
            get {
                return ResourceManager.GetString("ExceptionDeadlockDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity was not found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionEntityNotFound {
            get {
                return ResourceManager.GetString("ExceptionEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity version does not match the version in the database (OID: {0}). 的本地化字符串。
        /// </summary>
        internal static string ExceptionEntityVersion {
            get {
                return ResourceManager.GetString("ExceptionEntityVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The enumeration value {0} was not found for class {1}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionEnumValueNotFound {
            get {
                return ResourceManager.GetString("ExceptionEnumValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected string value. 的本地化字符串。
        /// </summary>
        internal static string ExceptionExpectedStringValue {
            get {
                return ResourceManager.GetString("ExceptionExpectedStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot inherit read-context as an update-context. 的本地化字符串。
        /// </summary>
        internal static string ExceptionIncompatiblePersistenceContext {
            get {
                return ResourceManager.GetString("ExceptionIncompatiblePersistenceContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionInvalidEntity {
            get {
                return ResourceManager.GetString("ExceptionInvalidEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persistence context required. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPersistenceContextRequired {
            get {
                return ResourceManager.GetString("ExceptionPersistenceContextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string RuleEmbeddeValue {
            get {
                return ResourceManager.GetString("RuleEmbeddeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more {0} are invalid. 的本地化字符串。
        /// </summary>
        internal static string RuleEmbeddeValueCollection {
            get {
                return ResourceManager.GetString("RuleEmbeddeValueCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be between {1} and {2} characters. 的本地化字符串。
        /// </summary>
        internal static string RuleLength {
            get {
                return ResourceManager.GetString("RuleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is required. 的本地化字符串。
        /// </summary>
        internal static string RuleRequired {
            get {
                return ResourceManager.GetString("RuleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} conflicts with an existing {1}. 的本地化字符串。
        /// </summary>
        internal static string RuleUniqueKey {
            get {
                return ResourceManager.GetString("RuleUniqueKey", resourceCulture);
            }
        }
    }
}
