//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Tools.Measurement {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Tools.Measurement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrate 的本地化字符串。
        /// </summary>
        public static string CalibrationDialogTitle {
            get {
                return ResourceManager.GetString("CalibrationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Elliptical ROI 的本地化字符串。
        /// </summary>
        public static string CommandCreateEllipiticalRoi {
            get {
                return ResourceManager.GetString("CommandCreateEllipiticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Polygonal ROI 的本地化字符串。
        /// </summary>
        public static string CommandCreatePolygonalRoi {
            get {
                return ResourceManager.GetString("CommandCreatePolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Protractor 的本地化字符串。
        /// </summary>
        public static string CommandCreateProtractor {
            get {
                return ResourceManager.GetString("CommandCreateProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Rectangle ROI 的本地化字符串。
        /// </summary>
        public static string CommandCreateRectangleRoi {
            get {
                return ResourceManager.GetString("CommandCreateRectangleRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Ruler 的本地化字符串。
        /// </summary>
        public static string CommandCreateRuler {
            get {
                return ResourceManager.GetString("CommandCreateRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot calibrate a ruler of zero-length. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotCalibrateZeroLengthRuler {
            get {
                return ResourceManager.GetString("ErrorCannotCalibrateZeroLengthRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ellipse {0} 的本地化字符串。
        /// </summary>
        public static string FormatEllipseName {
            get {
                return ResourceManager.GetString("FormatEllipseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon {0} 的本地化字符串。
        /// </summary>
        public static string FormatPolygonName {
            get {
                return ResourceManager.GetString("FormatPolygonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protractor {0} 的本地化字符串。
        /// </summary>
        public static string FormatProtractorName {
            get {
                return ResourceManager.GetString("FormatProtractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle {0} 的本地化字符串。
        /// </summary>
        public static string FormatRectangleName {
            get {
                return ResourceManager.GetString("FormatRectangleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruler {0} 的本地化字符串。
        /// </summary>
        public static string FormatRulerName {
            get {
                return ResourceManager.GetString("FormatRulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrate 的本地化字符串。
        /// </summary>
        public static string MenuCalibrationTool {
            get {
                return ResourceManager.GetString("MenuCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical ROI 的本地化字符串。
        /// </summary>
        public static string MenuEllipticalRoi {
            get {
                return ResourceManager.GetString("MenuEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量 的本地化字符串。
        /// </summary>
        public static string MenuMeasurement {
            get {
                return ResourceManager.GetString("MenuMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygonal ROI 的本地化字符串。
        /// </summary>
        public static string MenuPolygonalRoi {
            get {
                return ResourceManager.GetString("MenuPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protractor 的本地化字符串。
        /// </summary>
        public static string MenuProtractor {
            get {
                return ResourceManager.GetString("MenuProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangular ROI 的本地化字符串。
        /// </summary>
        public static string MenuRectangularRoi {
            get {
                return ResourceManager.GetString("MenuRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruler 的本地化字符串。
        /// </summary>
        public static string MenuRuler {
            get {
                return ResourceManager.GetString("MenuRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Angles 的本地化字符串。
        /// </summary>
        public static string MenuShowAngles {
            get {
                return ResourceManager.GetString("MenuShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length must be greater than 0 cm. 的本地化字符串。
        /// </summary>
        public static string MessageInvalidLength {
            get {
                return ResourceManager.GetString("MessageInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical ROI 的本地化字符串。
        /// </summary>
        public static string ToolbarEllipticalRoi {
            get {
                return ResourceManager.GetString("ToolbarEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygonal ROI 的本地化字符串。
        /// </summary>
        public static string ToolbarPolygonalRoi {
            get {
                return ResourceManager.GetString("ToolbarPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protractor 的本地化字符串。
        /// </summary>
        public static string ToolbarProtractor {
            get {
                return ResourceManager.GetString("ToolbarProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangular ROI 的本地化字符串。
        /// </summary>
        public static string ToolbarRectangularRoi {
            get {
                return ResourceManager.GetString("ToolbarRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruler 的本地化字符串。
        /// </summary>
        public static string ToolbarRuler {
            get {
                return ResourceManager.GetString("ToolbarRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Angles 的本地化字符串。
        /// </summary>
        public static string ToolbarShowAngles {
            get {
                return ResourceManager.GetString("ToolbarShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F1}° 的本地化字符串。
        /// </summary>
        public static string ToolsMeasurementFormatDegrees {
            get {
                return ResourceManager.GetString("ToolsMeasurementFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Vertex 的本地化字符串。
        /// </summary>
        public static string ToolsMeasurementSetVertex {
            get {
                return ResourceManager.GetString("ToolsMeasurementSetVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ° 的本地化字符串。
        /// </summary>
        public static string ToolsMeasurementUnitDegree {
            get {
                return ResourceManager.GetString("ToolsMeasurementUnitDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrate 的本地化字符串。
        /// </summary>
        public static string TooltipCalibrationTool {
            get {
                return ResourceManager.GetString("TooltipCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical ROI 的本地化字符串。
        /// </summary>
        public static string TooltipEllipticalRoi {
            get {
                return ResourceManager.GetString("TooltipEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygonal ROI 的本地化字符串。
        /// </summary>
        public static string TooltipPolygonalRoi {
            get {
                return ResourceManager.GetString("TooltipPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protractor 的本地化字符串。
        /// </summary>
        public static string TooltipProtractor {
            get {
                return ResourceManager.GetString("TooltipProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangular ROI 的本地化字符串。
        /// </summary>
        public static string TooltipRectangularRoi {
            get {
                return ResourceManager.GetString("TooltipRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ruler 的本地化字符串。
        /// </summary>
        public static string TooltipRuler {
            get {
                return ResourceManager.GetString("TooltipRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Angles 的本地化字符串。
        /// </summary>
        public static string TooltipShowAngles {
            get {
                return ResourceManager.GetString("TooltipShowAngles", resourceCulture);
            }
        }
    }
}
