//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class StandardModalitySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StandardModalitySettings defaultInstance = ((StandardModalitySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StandardModalitySettings())));
        
        public static StandardModalitySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// A list of standard DICOM modalities that can be used anywhere a list of modalities is required.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("A list of standard DICOM modalities that can be used anywhere a list of modalitie" +
            "s is required.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CR,CT,DOC,DX,ES,KO,MG,MR,NM,PR,OT,PT,RF,SC,US,XA")]
        public string Modalities {
            get {
                return ((string)(this["Modalities"]));
            }
        }
    }
}
