//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DicomPublishingSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DicomPublishingSettings defaultInstance = ((DicomPublishingSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DicomPublishingSettings())));
        
        public static DicomPublishingSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Specifies that created SOP instances are to be published to the Source AE as specified in the study&apos;s headers
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies that created SOP instances are to be published to the Source AE as spec" +
            "ified in the study\'s headers")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendLocalToStudySourceAE {
            get {
                return ((bool)(this["SendLocalToStudySourceAE"]));
            }
        }
    }
}
