//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputValidation() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InputValidation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The value must be between 1 and 100 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_ThrottleSettings_InvalidNumOfConnections {
            get {
                return ResourceManager.GetString("AdminDevices_ThrottleSettings_InvalidNumOfConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field must be a positive integer 的本地化字符串。
        /// </summary>
        internal static string AdminPartitionArchive_InvalidDelay {
            get {
                return ResourceManager.GetString("AdminPartitionArchive_InvalidDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This user group already exists. 的本地化字符串。
        /// </summary>
        internal static string AdminUserGroups_UserGroupAlreadyExists {
            get {
                return ResourceManager.GetString("AdminUserGroups_UserGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a comment for the reason for deleting the series for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingComment {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a name for the reason. 的本地化字符串。
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingName {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify the reason for deleting the series for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingReason {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a comment for the reason for deleting the studies for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingComment {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a name for the reason. 的本地化字符串。
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingName {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify the reason for deleting the studies for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingReason {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This AE Title already exists 的本地化字符串。
        /// </summary>
        internal static string DuplicateAETitle {
            get {
                return ResourceManager.GetString("DuplicateAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Age must contain only digits and may not be negative 的本地化字符串。
        /// </summary>
        internal static string EditStudyDialog_InvalidPatientAge {
            get {
                return ResourceManager.GetString("EditStudyDialog_InvalidPatientAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a comment for the reason for editing the studies for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string EditStudyDialog_MissingComment {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a name for the reason. 的本地化字符串。
        /// </summary>
        internal static string EditStudyDialog_MissingName {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify the reason for editing the studies for future auditing purposes. 的本地化字符串。
        /// </summary>
        internal static string EditStudyDialog_MissingReason {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email address is invalidly formatted. 的本地化字符串。
        /// </summary>
        internal static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Watermark must be between 1 and 99 and less than the Low Watermark 的本地化字符串。
        /// </summary>
        internal static string HighWatermark_InvalidRange {
            get {
                return ResourceManager.GetString("HighWatermark_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid AE Title 的本地化字符串。
        /// </summary>
        internal static string InvalidAETitle {
            get {
                return ResourceManager.GetString("InvalidAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Data Access Rule Condition 的本地化字符串。
        /// </summary>
        internal static string InvalidDataRule {
            get {
                return ResourceManager.GetString("InvalidDataRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid date: {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Folder Name is either invalid or is being used for another partition. 的本地化字符串。
        /// </summary>
        internal static string InvalidPartitionFolderName {
            get {
                return ResourceManager.GetString("InvalidPartitionFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an invalid DICOM Patient ID. 的本地化字符串。
        /// </summary>
        internal static string InvalidPatientID {
            get {
                return ResourceManager.GetString("InvalidPatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port must be between 1 and 65535 的本地化字符串。
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule must have a name 的本地化字符串。
        /// </summary>
        internal static string InvalidRuleName {
            get {
                return ResourceManager.GetString("InvalidRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid time 的本地化字符串。
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Watermark must be between 1 and 99 and less than the High Watermark 的本地化字符串。
        /// </summary>
        internal static string LowWatermark_InvalidRange {
            get {
                return ResourceManager.GetString("LowWatermark_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Person Name. Each field may contain up to 64 characters. 的本地化字符串。
        /// </summary>
        internal static string PersonNameInputPanel_InvalidName {
            get {
                return ResourceManager.GetString("PersonNameInputPanel_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value for Patient&apos;s Sex.  If you choose to use data in these images, Patient&apos;s Sex of the study will be set to Other. Howerver, you can still edit the study after the reconciliation has completed. 的本地化字符串。
        /// </summary>
        internal static string SIQ_ReconcileDialog_PatientSexOverriddenOnMerge {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDialog_PatientSexOverriddenOnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field is required 的本地化字符串。
        /// </summary>
        internal static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This user id already exists 的本地化字符串。
        /// </summary>
        internal static string UserIDAlreadyExists {
            get {
                return ResourceManager.GetString("UserIDAlreadyExists", resourceCulture);
            }
        }
    }
}
