//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accession # 的本地化字符串。
        /// </summary>
        internal static string AccessionNumber {
            get {
                return ResourceManager.GetString("AccessionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update Authority Group, the password entered is incorrect. 的本地化字符串。
        /// </summary>
        internal static string AddEditUserGroupsDialog_InvalidPassword {
            get {
                return ResourceManager.GetString("AddEditUserGroupsDialog_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling data access for an authority group removes the association between the authority group and imaging studies.  Users associated with the authority group will no longer be able to see their imaging studies.  Please re-enter your password to confirm this change. 的本地化字符串。
        /// </summary>
        internal static string AddEditUserGroups_DataAccessChanged {
            get {
                return ResourceManager.GetString("AddEditUserGroups_DataAccessChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: This change may not take effect immediately. 的本地化字符串。
        /// </summary>
        internal static string AddEditUserGroups_DataAccessChangedDelayWarning {
            get {
                return ResourceManager.GetString("AddEditUserGroups_DataAccessChangedDelayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Confirm Update 的本地化字符串。
        /// </summary>
        internal static string AddEditUserGroups_PasswordConfirmTitle {
            get {
                return ResourceManager.GetString("AddEditUserGroups_PasswordConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Server Partition configuration to ensure a copy of the study is maintained after deletion. 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_CheckPartitionConfiguration {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_CheckPartitionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this record? You will have to delete all backup files manually. 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_DeleteConfirmationDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_DeleteConfirmationDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify your search criteria. 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_ModifySearchCriteria {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_ModifySearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No studies found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_NoStudiesFound {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_NoStudiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study had not been archived at the time it was deleted. 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_StudyWasNotArchived {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_StudyWasNotArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove {0} from partition {1}? 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_DeleteDevice_AreYouSure {
            get {
                return ResourceManager.GetString("AdminDevices_DeleteDevice_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the maximum number of simultaneous connections Image Server can initiate for this device. 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_ThrottleSettings_Info {
            get {
                return ResourceManager.GetString("AdminDevices_ThrottleSettings_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No file systems were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string AdminFilesystem_NoFilesystemFound {
            get {
                return ResourceManager.GetString("AdminFilesystem_NoFilesystemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Archive Name 的本地化字符串。
        /// </summary>
        internal static string AdminPartitionArchive_AddEditDialog_ArchiveNameDefaultText {
            get {
                return ResourceManager.GetString("AdminPartitionArchive_AddEditDialog_ArchiveNameDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete partition archive &quot;{0}&quot; and all related settings permanently? 的本地化字符串。
        /// </summary>
        internal static string AdminPartitionArchive_DeleteDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminPartitionArchive_DeleteDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No partition archives were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string AdminPartitionArchive_NoArchiveFound {
            get {
                return ResourceManager.GetString("AdminPartitionArchive_NoArchiveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incoming studies will be placed in the Study Integrity Queue if the Study Instance UID matches an existing study and the data differs from any of the selected criteria below. 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_StudyMatchingInfo {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_StudyMatchingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select authority groups that will be granted access to this partition. 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_DataAccess_PleaseSelect {
            get {
                return ResourceManager.GetString("AdminPartition_DataAccess_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 authority group with access to all studies on accessible partitions 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_DataAccess_WarningAllStudiesAccess {
            get {
                return ResourceManager.GetString("AdminPartition_DataAccess_WarningAllStudiesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s recommended that you disable the partition instead of deleting it.
        ///
        ///Are you sure you still want to delete partition {0} and all related settings permanently? 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_DeletePartitionDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminPartition_DeletePartitionDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server partition {0} has been removed.
        ///
        ///At least one server partition is required. Please add a new server partition. 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_DeletePartition_Successful_AddOneNow {
            get {
                return ResourceManager.GetString("AdminPartition_DeletePartition_Successful_AddOneNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No server partitions were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_NoPartitionsFound {
            get {
                return ResourceManager.GetString("AdminPartition_NoPartitionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove rule &quot;{0}&quot; from partition {1}? 的本地化字符串。
        /// </summary>
        internal static string AdminServerRules_DeleteDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminServerRules_DeleteDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete authority group &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string AdminUserGroups_DeleteDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminUserGroups_DeleteDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Are you sure you want to delete this group? 的本地化字符串。
        /// </summary>
        internal static string AdminUserGroup_DeleteNonEmptyGroupDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminUserGroup_DeleteNonEmptyGroupDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete user &quot;{0}&quot; ({1})? 的本地化字符串。
        /// </summary>
        internal static string AdminUser_DeleteDialog_AreYouSure {
            get {
                return ResourceManager.GetString("AdminUser_DeleteDialog_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password for {0} has been reset. 的本地化字符串。
        /// </summary>
        internal static string AdminUser_PasswordReset {
            get {
                return ResourceManager.GetString("AdminUser_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete all of the current Alert items? &lt;br/&gt;Only the alerts that are a result of the current search will be deleted. 的本地化字符串。
        /// </summary>
        internal static string AlertDeleteAllConfirm {
            get {
                return ResourceManager.GetString("AlertDeleteAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item from the queue? 的本地化字符串。
        /// </summary>
        internal static string AlertDeleteConfirm {
            get {
                return ResourceManager.GetString("AlertDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no study information for this item. 的本地化字符串。
        /// </summary>
        internal static string AlertNoStudyInformationForThisItem {
            get {
                return ResourceManager.GetString("AlertNoStudyInformationForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any 的本地化字符串。
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No log entries found matching the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string AppLogNotFound {
            get {
                return ResourceManager.GetString("AppLogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter search criteria to find log entries. 的本地化字符串。
        /// </summary>
        internal static string AppLogPleaseEnterSearchCriteria {
            get {
                return ResourceManager.GetString("AppLogPleaseEnterSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This archive queue item is being processed. Try again later. 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueueBeingProcessed {
            get {
                return ResourceManager.GetString("ArchiveQueueBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This archive queue item is no longer available in the system 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueueNotAvailable {
            get {
                return ResourceManager.GetString("ArchiveQueueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reset this item to Pending? 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueueResetConfirm {
            get {
                return ResourceManager.GetString("ArchiveQueueResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reset this archive queue item. Please contact server administrator. 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueueResetFailed {
            get {
                return ResourceManager.GetString("ArchiveQueueResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reprocess this study? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureToReprocessThisStudy {
            get {
                return ResourceManager.GetString("AreYouSureToReprocessThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macro Documentation 的本地化字符串。
        /// </summary>
        internal static string CCDocumentation {
            get {
                return ResourceManager.GetString("CCDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageServer User&apos;s Guide 的本地化字符串。
        /// </summary>
        internal static string CCImageServerUsersGuide {
            get {
                return ResourceManager.GetString("CCImageServerUsersGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Confirm 的本地化字符串。
        /// </summary>
        internal static string ConfirmDialogDefault {
            get {
                return ResourceManager.GetString("ConfirmDialogDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ConfirmDialogError {
            get {
                return ResourceManager.GetString("ConfirmDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please contact the administrators. 的本地化字符串。
        /// </summary>
        internal static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- Custom Reason -- 的本地化字符串。
        /// </summary>
        internal static string CustomReason {
            get {
                return ResourceManager.GetString("CustomReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Custom Reason Comment 的本地化字符串。
        /// </summary>
        internal static string CustomReasonComment {
            get {
                return ResourceManager.GetString("CustomReasonComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected studies were moved to the work queue for deletion. 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmationPlural {
            get {
                return ResourceManager.GetString("DeleteConfirmationPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected study was moved to the work queue for deletion. 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmationSingle {
            get {
                return ResourceManager.GetString("DeleteConfirmationSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the following series? 的本地化字符串。
        /// </summary>
        internal static string DeleteSeriesMessage {
            get {
                return ResourceManager.GetString("DeleteSeriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEVICEAE 的本地化字符串。
        /// </summary>
        internal static string DeviceAE {
            get {
                return ResourceManager.GetString("DeviceAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 104 的本地化字符串。
        /// </summary>
        internal static string DeviceDefaultPort {
            get {
                return ResourceManager.GetString("DeviceDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DHCP 的本地化字符串。
        /// </summary>
        internal static string DHCP {
            get {
                return ResourceManager.GetString("DHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Data Access Rule 的本地化字符串。
        /// </summary>
        internal static string DialogAddDataRuleTitle {
            get {
                return ResourceManager.GetString("DialogAddDataRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Device 的本地化字符串。
        /// </summary>
        internal static string DialogAddDeviceTitle {
            get {
                return ResourceManager.GetString("DialogAddDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add File System 的本地化字符串。
        /// </summary>
        internal static string DialogAddFileSystemTitle {
            get {
                return ResourceManager.GetString("DialogAddFileSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Partition 的本地化字符串。
        /// </summary>
        internal static string DialogAddPartitionTitle {
            get {
                return ResourceManager.GetString("DialogAddPartitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Server Rule 的本地化字符串。
        /// </summary>
        internal static string DialogAddServerRuleTitle {
            get {
                return ResourceManager.GetString("DialogAddServerRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Token 的本地化字符串。
        /// </summary>
        internal static string DialogAddTokenTitle {
            get {
                return ResourceManager.GetString("DialogAddTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Authority Group 的本地化字符串。
        /// </summary>
        internal static string DialogAddUserGroupTitle {
            get {
                return ResourceManager.GetString("DialogAddUserGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add User 的本地化字符串。
        /// </summary>
        internal static string DialogAddUserTitle {
            get {
                return ResourceManager.GetString("DialogAddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Data Access Rule 的本地化字符串。
        /// </summary>
        internal static string DialogEditDataRuleTitle {
            get {
                return ResourceManager.GetString("DialogEditDataRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Device 的本地化字符串。
        /// </summary>
        internal static string DialogEditDeviceTitle {
            get {
                return ResourceManager.GetString("DialogEditDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit File System 的本地化字符串。
        /// </summary>
        internal static string DialogEditFileSystemTitle {
            get {
                return ResourceManager.GetString("DialogEditFileSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Partition 的本地化字符串。
        /// </summary>
        internal static string DialogEditPartitionTitle {
            get {
                return ResourceManager.GetString("DialogEditPartitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Server Rule 的本地化字符串。
        /// </summary>
        internal static string DialogEditServerRuleTitle {
            get {
                return ResourceManager.GetString("DialogEditServerRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Token 的本地化字符串。
        /// </summary>
        internal static string DialogEditTokenTitle {
            get {
                return ResourceManager.GetString("DialogEditTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Authority Group 的本地化字符串。
        /// </summary>
        internal static string DialogEditUserGroupTitle {
            get {
                return ResourceManager.GetString("DialogEditUserGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit User 的本地化字符串。
        /// </summary>
        internal static string DialogEditUserTitle {
            get {
                return ResourceManager.GetString("DialogEditUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} by {1} 的本地化字符串。
        /// </summary>
        internal static string EditBy {
            get {
                return ResourceManager.GetString("EditBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggestions: 的本地化字符串。
        /// </summary>
        internal static string EmptySearchResult_Suggestions {
            get {
                return ResourceManager.GetString("EmptySearchResult_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For further assistance, try the following links: 的本地化字符串。
        /// </summary>
        internal static string ForFurtherAssistanceTryTheFollowingLinks {
            get {
                return ResourceManager.GetString("ForFurtherAssistanceTryTheFollowingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alerts Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerAlertMultipleItemsFound {
            get {
                return ResourceManager.GetString("GridPagerAlertMultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerAlertSingleItemFound {
            get {
                return ResourceManager.GetString("GridPagerAlertSingleItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerApplicationLogMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerApplicationLogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerApplicationLogSingleItem {
            get {
                return ResourceManager.GetString("GridPagerApplicationLogSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Tokens Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerAuthorityTokenMultipleItemsFound {
            get {
                return ResourceManager.GetString("GridPagerAuthorityTokenMultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Token Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerAuthorityTokenSingleItemFound {
            get {
                return ResourceManager.GetString("GridPagerAuthorityTokenSingleItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerDeviceMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerDeviceMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerDeviceSingleItem {
            get {
                return ResourceManager.GetString("GridPagerDeviceSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Systems found 的本地化字符串。
        /// </summary>
        internal static string GridPagerFileSystemMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerFileSystemMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File System found 的本地化字符串。
        /// </summary>
        internal static string GridPagerFileSystemSingleItem {
            get {
                return ResourceManager.GetString("GridPagerFileSystemSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  |  的本地化字符串。
        /// </summary>
        internal static string GridPagerLineSpacer {
            get {
                return ResourceManager.GetString("GridPagerLineSpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 next &gt; 的本地化字符串。
        /// </summary>
        internal static string GridPagerNext {
            get {
                return ResourceManager.GetString("GridPagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partitions Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerPartitionMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerPartitionMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerPartitionSingleItem {
            get {
                return ResourceManager.GetString("GridPagerPartitionSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt; previous 的本地化字符串。
        /// </summary>
        internal static string GridPagerPrevious {
            get {
                return ResourceManager.GetString("GridPagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerServerRulesMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerServerRulesMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerServerRulesSingleItem {
            get {
                return ResourceManager.GetString("GridPagerServerRulesSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Services Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerServiceMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerServiceMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerServiceSingleItem {
            get {
                return ResourceManager.GetString("GridPagerServiceSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Studies Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerStudyMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerStudyMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerStudySingleItem {
            get {
                return ResourceManager.GetString("GridPagerStudySingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Groups Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerUserGroupsMultipleItemsFound {
            get {
                return ResourceManager.GetString("GridPagerUserGroupsMultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Group Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerUserGroupsSingleItemFound {
            get {
                return ResourceManager.GetString("GridPagerUserGroupsSingleItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerUserMultipleItemsFound {
            get {
                return ResourceManager.GetString("GridPagerUserMultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerUserSingleItemFound {
            get {
                return ResourceManager.GetString("GridPagerUserSingleItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Items Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerWorkQueueMultipleItems {
            get {
                return ResourceManager.GetString("GridPagerWorkQueueMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Item Found 的本地化字符串。
        /// </summary>
        internal static string GridPagerWorkQueueSingleItem {
            get {
                return ResourceManager.GetString("GridPagerWorkQueueSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High watermark 的本地化字符串。
        /// </summary>
        internal static string HighWatermark {
            get {
                return ResourceManager.GetString("HighWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageServer Developers Forum 的本地化字符串。
        /// </summary>
        internal static string ImageServerDevelopersForum {
            get {
                return ResourceManager.GetString("ImageServerDevelopersForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageServer Users Forum 的本地化字符串。
        /// </summary>
        internal static string ImageServerUsersForum {
            get {
                return ResourceManager.GetString("ImageServerUsersForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- ANY -- 的本地化字符串。
        /// </summary>
        internal static string LogLevelAny {
            get {
                return ResourceManager.GetString("LogLevelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR 的本地化字符串。
        /// </summary>
        internal static string LogLevelError {
            get {
                return ResourceManager.GetString("LogLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INFO 的本地化字符串。
        /// </summary>
        internal static string LogLevelInfo {
            get {
                return ResourceManager.GetString("LogLevelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARN 的本地化字符串。
        /// </summary>
        internal static string LogLevelWarning {
            get {
                return ResourceManager.GetString("LogLevelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low watermark 的本地化字符串。
        /// </summary>
        internal static string LowWatermark {
            get {
                return ResourceManager.GetString("LowWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Months 的本地化字符串。
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following series will be moved to {0}: 的本地化字符串。
        /// </summary>
        internal static string MoveSeriesMessage {
            get {
                return ResourceManager.GetString("MoveSeriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following studies will be moved to {0}: 的本地化字符串。
        /// </summary>
        internal static string MoveStudyMessage {
            get {
                return ResourceManager.GetString("MoveStudyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete these Alert items? 的本地化字符串。
        /// </summary>
        internal static string MultipleAlertDelete {
            get {
                return ResourceManager.GetString("MultipleAlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete these Archive Queue items? 的本地化字符串。
        /// </summary>
        internal static string MultipleArchiveQueueDelete {
            get {
                return ResourceManager.GetString("MultipleArchiveQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reset these items to Pending? 的本地化字符串。
        /// </summary>
        internal static string MultipleArchiveQueueResetConfirm {
            get {
                return ResourceManager.GetString("MultipleArchiveQueueResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete these Restore Queue Items? 的本地化字符串。
        /// </summary>
        internal static string MultipleRestoreQueueDelete {
            get {
                return ResourceManager.GetString("MultipleRestoreQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the following studies? 的本地化字符串。
        /// </summary>
        internal static string MultipleStudyDelete {
            get {
                return ResourceManager.GetString("MultipleStudyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete these items? 的本地化字符串。
        /// </summary>
        internal static string MultipleStudyIntegrityQueueDelete {
            get {
                return ResourceManager.GetString("MultipleStudyIntegrityQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to restore the following studies? 的本地化字符串。
        /// </summary>
        internal static string MultipleStudyRestore {
            get {
                return ResourceManager.GetString("MultipleStudyRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No alerts were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoAlertsFound {
            get {
                return ResourceManager.GetString("NoAlertsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items were found using the provided criteria 的本地化字符串。
        /// </summary>
        internal static string NoArchiveQueueItemFound {
            get {
                return ResourceManager.GetString("NoArchiveQueueItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No devices were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoDevicesWereFound {
            get {
                return ResourceManager.GetString("NoDevicesWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No DHCP 的本地化字符串。
        /// </summary>
        internal static string NoDHCP {
            get {
                return ResourceManager.GetString("NoDHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 With no filters specified, this search may return a large number of studies.&lt;br/&gt;Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string NoFiltersSearchWarning {
            get {
                return ResourceManager.GetString("NoFiltersSearchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None Specified 的本地化字符串。
        /// </summary>
        internal static string NoneSpecified {
            get {
                return ResourceManager.GetString("NoneSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome. 的本地化字符串。
        /// </summary>
        internal static string NonStandardInstallation {
            get {
                return ResourceManager.GetString("NonStandardInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No server partition has been set up or you do not have the permission to access any partitions. 的本地化字符串。
        /// </summary>
        internal static string NoPartitionAvailable {
            get {
                return ResourceManager.GetString("NoPartitionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No server partition has been created. 的本地化字符串。
        /// </summary>
        internal static string NoPartitionCreated {
            get {
                return ResourceManager.GetString("NoPartitionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoRestoreQueueItemFound {
            get {
                return ResourceManager.GetString("NoRestoreQueueItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No server rules were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoServerRulesFound {
            get {
                return ResourceManager.GetString("NoServerRulesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No services were found using the provided criteria 的本地化字符串。
        /// </summary>
        internal static string NoServicesFound {
            get {
                return ResourceManager.GetString("NoServicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoSIQItemsFound {
            get {
                return ResourceManager.GetString("NoSIQItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No studies found matching the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoStudiesFound {
            get {
                return ResourceManager.GetString("NoStudiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No studies were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoStudiesWereFound {
            get {
                return ResourceManager.GetString("NoStudiesWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Default 的本地化字符串。
        /// </summary>
        internal static string NotDefault {
            get {
                return ResourceManager.GetString("NotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Specified 的本地化字符串。
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Authority Groups were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoUserGroupsFound {
            get {
                return ResourceManager.GetString("NoUserGroupsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No users were found using the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No work queue items found matching the provided criteria. 的本地化字符串。
        /// </summary>
        internal static string NoWorkQueueFound {
            get {
                return ResourceManager.GetString("NoWorkQueueFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition 的本地化字符串。
        /// </summary>
        internal static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive exists, studies may become nearline. 的本地化字符串。
        /// </summary>
        internal static string PartitionStorageConfiguration_ArchiveConfiguredNoDeleteRule {
            get {
                return ResourceManager.GetString("PartitionStorageConfiguration_ArchiveConfiguredNoDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete rule enabled, older studies may be deleted. 的本地化字符串。
        /// </summary>
        internal static string PartitionStorageConfiguration_DeleteRuleExists {
            get {
                return ResourceManager.GetString("PartitionStorageConfiguration_DeleteRuleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New processed studies will now be kept online. 的本地化字符串。
        /// </summary>
        internal static string PartitionStorageConfiguration_NoArchiveConfiguredNoDeleteRule {
            get {
                return ResourceManager.GetString("PartitionStorageConfiguration_NoArchiveConfiguredNoDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient ID 的本地化字符串。
        /// </summary>
        internal static string PatientID {
            get {
                return ResourceManager.GetString("PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Name 的本地化字符串。
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter search criteria to find studies. 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterSearchCriteriaToFindStudies {
            get {
                return ResourceManager.GetString("PleaseEnterSearchCriteriaToFindStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study could not be scheduled for reprocess. Please contact server administrator. 的本地化字符串。
        /// </summary>
        internal static string ReprocessFailed {
            get {
                return ResourceManager.GetString("ReprocessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study has been scheduled for reprocess. 的本地化字符串。
        /// </summary>
        internal static string ReprocessOK {
            get {
                return ResourceManager.GetString("ReprocessOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reprocess Study via GUI 的本地化字符串。
        /// </summary>
        internal static string ReprocessStudyViaGUI {
            get {
                return ResourceManager.GetString("ReprocessStudyViaGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the search criteria to search for entries. 的本地化字符串。
        /// </summary>
        internal static string RestoreQueuePleaseEnterSearchCriteria {
            get {
                return ResourceManager.GetString("RestoreQueuePleaseEnterSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- Select All -- 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item you selected is no longer on the list.&lt;br/&gt;It could have been modified by the system or another person. 的本地化字符串。
        /// </summary>
        internal static string SelectedWorkQueueNoLongerOnTheList {
            get {
                return ResourceManager.GetString("SelectedWorkQueueNoLongerOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- Select One -- 的本地化字符串。
        /// </summary>
        internal static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Series Items for this study. 的本地化字符串。
        /// </summary>
        internal static string SeriesDetails_NoSeriesForThisStudy {
            get {
                return ResourceManager.GetString("SeriesDetails_NoSeriesForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This server is configured with a Partition Archive and will store studies permanently. 的本地化字符串。
        /// </summary>
        internal static string ServerModeArchive {
            get {
                return ResourceManager.GetString("ServerModeArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This server is configured with a Partition Archive and as a temporary cache. 的本地化字符串。
        /// </summary>
        internal static string ServerModeMixedMode {
            get {
                return ResourceManager.GetString("ServerModeMixedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This server is configured to operate as a temporary cache. 的本地化字符串。
        /// </summary>
        internal static string ServerModeTemporaryCache {
            get {
                return ResourceManager.GetString("ServerModeTemporaryCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update this service lock. Please contact the server administrator. 的本地化字符串。
        /// </summary>
        internal static string ServiceLockUpdateFailed_ContactAdmin {
            get {
                return ResourceManager.GetString("ServiceLockUpdateFailed_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This service lock is being used by the server.  Are you sure you want to edit it ? 的本地化字符串。
        /// </summary>
        internal static string ServiceLockUpdate_Confirm_ServiceIsLocked {
            get {
                return ResourceManager.GetString("ServiceLockUpdate_Confirm_ServiceIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No activity is detected. For security reasons, this session will end in {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string SessionTimeoutCountdownMessage {
            get {
                return ResourceManager.GetString("SessionTimeoutCountdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this Alert item? 的本地化字符串。
        /// </summary>
        internal static string SingleAlertDelete {
            get {
                return ResourceManager.GetString("SingleAlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this Archive Queue item? 的本地化字符串。
        /// </summary>
        internal static string SingleArchiveQueueDelete {
            get {
                return ResourceManager.GetString("SingleArchiveQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this Restore Queue Item? 的本地化字符串。
        /// </summary>
        internal static string SingleRestoreQueueDelete {
            get {
                return ResourceManager.GetString("SingleRestoreQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this study? 的本地化字符串。
        /// </summary>
        internal static string SingleStudyDelete {
            get {
                return ResourceManager.GetString("SingleStudyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this Item? 的本地化字符串。
        /// </summary>
        internal static string SingleStudyIntegrityQueueDelete {
            get {
                return ResourceManager.GetString("SingleStudyIntegrityQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to restore this study? 的本地化字符串。
        /// </summary>
        internal static string SingleStudyRestore {
            get {
                return ResourceManager.GetString("SingleStudyRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicting images contain information which is too long and will be truncated 的本地化字符串。
        /// </summary>
        internal static string SIQ_DataMayBeTruncated {
            get {
                return ResourceManager.GetString("SIQ_DataMayBeTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING: Duplicates contain information which does not match the existing study. The information in the study (and all existing images) will be replaced. 的本地化字符串。
        /// </summary>
        internal static string SIQ_ReconcileDuplicateDialog_UseDuplicateWarning {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDuplicateDialog_UseDuplicateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING: Duplicates contain information which does not match the existing study. This information will be lost when the existing SOPs are overwritten. 的本地化字符串。
        /// </summary>
        internal static string SIQ_ReconcileDuplicateDialog_UseExistingWarning {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDuplicateDialog_UseExistingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study is being processed. 的本地化字符串。
        /// </summary>
        internal static string StudyBeingProcessed {
            get {
                return ResourceManager.GetString("StudyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Date 的本地化字符串。
        /// </summary>
        internal static string StudyDate {
            get {
                return ResourceManager.GetString("StudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete duplicate SOPs. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Duplicate_Delete {
            get {
                return ResourceManager.GetString("StudyDetails_History_Duplicate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite existing SOPs and preserve data in duplicates. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Duplicate_OverwriteAsIs {
            get {
                return ResourceManager.GetString("StudyDetails_History_Duplicate_OverwriteAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite existing SOPs and update study with information in duplicates. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Duplicate_OverwriteWithDuplicateData {
            get {
                return ResourceManager.GetString("StudyDetails_History_Duplicate_OverwriteWithDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite existing SOPs and use the existing study information. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Duplicate_OverwriteWithExistingData {
            get {
                return ResourceManager.GetString("StudyDetails_History_Duplicate_OverwriteWithExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performed by {0} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Duplicate_PerformedBy {
            get {
                return ResourceManager.GetString("StudyDetails_History_Duplicate_PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} series were deleted by {1} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_MultipleSeriesDeletedBy {
            get {
                return ResourceManager.GetString("StudyDetails_History_MultipleSeriesDeletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} series was deleted by {1} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_OneSeriesDeletedBy {
            get {
                return ResourceManager.GetString("StudyDetails_History_OneSeriesDeletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performed By {0} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Reconcile_PerformedBy {
            get {
                return ResourceManager.GetString("StudyDetails_History_Reconcile_PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study was reprocessed. Reason: {0} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Reconcile_ReprocessedBecause {
            get {
                return ResourceManager.GetString("StudyDetails_History_Reconcile_ReprocessedBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study was reprocessed by {0}. Reason: {1} 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_History_Reconcile_ReprocessedByBecause {
            get {
                return ResourceManager.GetString("StudyDetails_History_Reconcile_ReprocessedByBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump to other authority groups 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_JumpToNonUpdatableGroupListingSectionLink {
            get {
                return ResourceManager.GetString("StudyDetails_JumpToNonUpdatableGroupListingSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Archive Queue items for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoArchiveQueueItemForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoArchiveQueueItemForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Archive Study Storage items for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoArchiveStudyStorageForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoArchiveStudyStorageForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data Access Authority Groups assigned to this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoAuthorityGroupsForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoAuthorityGroupsForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No File System Queue items for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoFileSystemForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoFileSystemForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No history record exists for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoHistoryItemForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoHistoryItemForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following authority group(s) also have access to this study due to administrative tokens: 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NonUpdatableGroupListingSectionTitle {
            get {
                return ResourceManager.GetString("StudyDetails_NonUpdatableGroupListingSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study does not contain any series. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoSeriesForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoSeriesForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No reconcile items for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoSIQForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoSIQForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Study Storage details for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoStudyStorageForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoStudyStorageForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Work Queue items for this study. 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_NoWorkQueueForThisStudy {
            get {
                return ResourceManager.GetString("StudyDetails_NoWorkQueueForThisStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discarded conflicting images 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_Reconcile_Discard_Description {
            get {
                return ResourceManager.GetString("StudyDetails_Reconcile_Discard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merged study and conflicting images 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_Reconcile_Merge_Description {
            get {
                return ResourceManager.GetString("StudyDetails_Reconcile_Merge_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created new study from conflicting images 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_Reconcile_NewStudy_Description {
            get {
                return ResourceManager.GetString("StudyDetails_Reconcile_NewStudy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processed the images normally 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_Reconcile_ProcessAsIs_Description {
            get {
                return ResourceManager.GetString("StudyDetails_Reconcile_ProcessAsIs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study was not modified 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_StudyWasNoChanged {
            get {
                return ResourceManager.GetString("StudyDetails_StudyWasNoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following Data Access authority group(s) currently have access to this study: 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_UpdatableDataAccessGroupListingSectionTitle {
            get {
                return ResourceManager.GetString("StudyDetails_UpdatableDataAccessGroupListingSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edited using Web GUI 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_WebEdit_Description {
            get {
                return ResourceManager.GetString("StudyDetails_WebEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edited by external web service 的本地化字符串。
        /// </summary>
        internal static string StudyDetails_WebServiceEdit_Description {
            get {
                return ResourceManager.GetString("StudyDetails_WebServiceEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Instance UID 的本地化字符串。
        /// </summary>
        internal static string StudyInstanceUID {
            get {
                return ResourceManager.GetString("StudyInstanceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study is not online. 的本地化字符串。
        /// </summary>
        internal static string StudyIsNearline {
            get {
                return ResourceManager.GetString("StudyIsNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study needs to be reconciled. 的本地化字符串。
        /// </summary>
        internal static string StudyRequiresReconcilie {
            get {
                return ResourceManager.GetString("StudyRequiresReconcilie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study has been scheduled for deletion. 的本地化字符串。
        /// </summary>
        internal static string StudyScheduledForDeletion {
            get {
                return ResourceManager.GetString("StudyScheduledForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study has been scheduled for editing. 的本地化字符串。
        /// </summary>
        internal static string StudyScheduledForEdit {
            get {
                return ResourceManager.GetString("StudyScheduledForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This study has been scheduled for reconciliation. 的本地化字符串。
        /// </summary>
        internal static string StudyScheduledForReconcile {
            get {
                return ResourceManager.GetString("StudyScheduledForReconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: this study contains attachment(s) which must be examined AFTER the edit to ensure all information is consistent. 的本地化字符串。
        /// </summary>
        internal static string WarningEditStudyWithAttachment {
            get {
                return ResourceManager.GetString("WarningEditStudyWithAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple matching studies have been found. Please select a study to view. 的本地化字符串。
        /// </summary>
        internal static string WebViewerMutipleMatchingStudiesFound {
            get {
                return ResourceManager.GetString("WebViewerMutipleMatchingStudiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weeks 的本地化字符串。
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This work queue item is being processed. Try again later. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueBeingProcessed {
            get {
                return ResourceManager.GetString("WorkQueueBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete this item. It is being processed by the server. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueBeingProcessed_CannotDelete {
            get {
                return ResourceManager.GetString("WorkQueueBeingProcessed_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item is being processed. It cannot be rescheduled at this point.&lt;br&gt;Please retry again later. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueBeingProcessed_CannotReschedule {
            get {
                return ResourceManager.GetString("WorkQueueBeingProcessed_CannotReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item from the queue? 的本地化字符串。
        /// </summary>
        internal static string WorkQueueDeleteConfirm {
            get {
                return ResourceManager.GetString("WorkQueueDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing an External Edit WorkQueue entry may cause the demographics for the study to be incorrect.  Are you sure you want to delete this item from the queue? 的本地化字符串。
        /// </summary>
        internal static string WorkQueueDeleteConfirmExternalEdit {
            get {
                return ResourceManager.GetString("WorkQueueDeleteConfirmExternalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete this work queue item. Please contact server administrator. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueDeleteFailed {
            get {
                return ResourceManager.GetString("WorkQueueDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete this work queue item.&lt;br&gt;Error: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkQueueDeleteFailed_WithException {
            get {
                return ResourceManager.GetString("WorkQueueDeleteFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: deleting this WorkQueue item may result in loss of images or incorrect study information! 的本地化字符串。
        /// </summary>
        internal static string WorkQueueDeleteWarning {
            get {
                return ResourceManager.GetString("WorkQueueDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has already failed. It cannot be rescheduled. Try reset it instead. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueFailed_CannotReschedule {
            get {
                return ResourceManager.GetString("WorkQueueFailed_CannotReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more items is no longer available. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueNoLongerAvailable {
            get {
                return ResourceManager.GetString("WorkQueueNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This work queue item is no longer available in the system 的本地化字符串。
        /// </summary>
        internal static string WorkQueueNotAvailable {
            get {
                return ResourceManager.GetString("WorkQueueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter search criteria to find work queue items. 的本地化字符串。
        /// </summary>
        internal static string WorkQueuePleaseEnterSearchCritera {
            get {
                return ResourceManager.GetString("WorkQueuePleaseEnterSearchCritera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reschedule the selected item because it is being processed. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleConfirm_ItemBeingProcessed {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleConfirm_ItemBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reschedule the selected item because it is being processed.  的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleConfirm_OneOrMoreAreBeingProcessed {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleConfirm_OneOrMoreAreBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reschedule this/these work queue item: {0} 的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleFailed_Exception {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleFailed_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot reschedule this workqueue item because it has failed. Try reset it instead. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleFailed_ItemHasFailed {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleFailed_ItemHasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more items you selected is no longer available and therefore will not be updated 的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleFailed_ItemNotAvailable {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleFailed_ItemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schedule start time must be in the future. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueRescheduleFailed_MustBeInFuture {
            get {
                return ResourceManager.GetString("WorkQueueRescheduleFailed_MustBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reset this item to Pending? 的本地化字符串。
        /// </summary>
        internal static string WorkQueueResetConfirm {
            get {
                return ResourceManager.GetString("WorkQueueResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reset this work queue item. Please contact server administrator.&lt;P&gt;{0} 的本地化字符串。
        /// </summary>
        internal static string WorkQueueResetFailed {
            get {
                return ResourceManager.GetString("WorkQueueResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item has been successfully deleted from the Work Queue. 的本地化字符串。
        /// </summary>
        internal static string WorkQueueSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("WorkQueueSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Years 的本地化字符串。
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your password has expired, or this is your first login to the ImageServer. Please enter a new password below. 的本地化字符串。
        /// </summary>
        internal static string YourPasswordHasExpired {
            get {
                return ResourceManager.GetString("YourPasswordHasExpired", resourceCulture);
            }
        }
    }
}
