//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Titles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About | {0} 的本地化字符串。
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Data Access Authority Groups to Studies 的本地化字符串。
        /// </summary>
        internal static string AddAuthorityGroupsDialogTitle {
            get {
                return ResourceManager.GetString("AddAuthorityGroupsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Partition Archive 的本地化字符串。
        /// </summary>
        internal static string AddPartitionArchiveTitle {
            get {
                return ResourceManager.GetString("AddPartitionArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm 的本地化字符串。
        /// </summary>
        internal static string AdminDeletedStudies_DeleteConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("AdminDeletedStudies_DeleteConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Information 的本地化字符串。
        /// </summary>
        internal static string AdminDeleteStudies_DetailsDialog_ArchiveInfoTabTitle {
            get {
                return ResourceManager.GetString("AdminDeleteStudies_DetailsDialog_ArchiveInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Information 的本地化字符串。
        /// </summary>
        internal static string AdminDeleteStudies_DetailsDialog_StudyInfoTabTitle {
            get {
                return ResourceManager.GetString("AdminDeleteStudies_DetailsDialog_StudyInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Features 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_AddEditDialog_FeaturesTabTitle {
            get {
                return ResourceManager.GetString("AdminDevices_AddEditDialog_FeaturesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_AddEditDialog_GeneralTabTitle {
            get {
                return ResourceManager.GetString("AdminDevices_AddEditDialog_GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throttle 的本地化字符串。
        /// </summary>
        internal static string AdminDevices_AddEditDialog_ThrottleTabTitle {
            get {
                return ResourceManager.GetString("AdminDevices_AddEditDialog_ThrottleTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string AdminFilesystem_AddEditDialog_GeneralTabTitle {
            get {
                return ResourceManager.GetString("AdminFilesystem_AddEditDialog_GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watermarks 的本地化字符串。
        /// </summary>
        internal static string AdminFilesystem_AddEditDialog_WatermarksTabTitle {
            get {
                return ResourceManager.GetString("AdminFilesystem_AddEditDialog_WatermarksTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Access 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_DataAccessTabTitle {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_DataAccessTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Management 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_DeleteManagementTabTitle {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_DeleteManagementTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_GeneralTabTitle {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Devices 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_RemoteDevicesTabTitle {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_RemoteDevicesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Matching 的本地化字符串。
        /// </summary>
        internal static string AdminPartition_AddEditDialog_StudyMatchingTabTitle {
            get {
                return ResourceManager.GetString("AdminPartition_AddEditDialog_StudyMatchingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string AdminServerRules_AddEditDialog_GeneralTabTitle {
            get {
                return ResourceManager.GetString("AdminServerRules_AddEditDialog_GeneralTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule XML 的本地化字符串。
        /// </summary>
        internal static string AdminServerRules_AddEditDialog_RuleXMLTabTitle {
            get {
                return ResourceManager.GetString("AdminServerRules_AddEditDialog_RuleXMLTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Service Schedule 的本地化字符串。
        /// </summary>
        internal static string AdminServices_EditDialogTitle {
            get {
                return ResourceManager.GetString("AdminServices_EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Reset 的本地化字符串。
        /// </summary>
        internal static string AdminUser_PasswordResetDialogTitle {
            get {
                return ResourceManager.GetString("AdminUser_PasswordResetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alerts 的本地化字符串。
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alerts | {0} 的本地化字符串。
        /// </summary>
        internal static string AlertsPageTitle {
            get {
                return ResourceManager.GetString("AlertsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Log 的本地化字符串。
        /// </summary>
        internal static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Log | {0} 的本地化字符串。
        /// </summary>
        internal static string ApplicationLogPageTitle {
            get {
                return ResourceManager.GetString("ApplicationLogPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive 的本地化字符串。
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Queue 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueue {
            get {
                return ResourceManager.GetString("ArchiveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Queue | {0} 的本地化字符串。
        /// </summary>
        internal static string ArchiveQueuePageTitle {
            get {
                return ResourceManager.GetString("ArchiveQueuePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audit 的本地化字符串。
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Tokens 的本地化字符串。
        /// </summary>
        internal static string AuthorityTokens {
            get {
                return ResourceManager.GetString("AuthorityTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization Error 的本地化字符串。
        /// </summary>
        internal static string AuthorizationErrorPageTitle {
            get {
                return ResourceManager.GetString("AuthorizationErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string ChangePasswordDialogTitle {
            get {
                return ResourceManager.GetString("ChangePasswordDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies Required 的本地化字符串。
        /// </summary>
        internal static string CookiesRequiredPageTitle {
            get {
                return ResourceManager.GetString("CookiesRequiredPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageServer Dashboard 的本地化字符串。
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        internal static string DashboardMenu {
            get {
                return ResourceManager.GetString("DashboardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard | {0} 的本地化字符串。
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Access 的本地化字符串。
        /// </summary>
        internal static string DataAccess {
            get {
                return ResourceManager.GetString("DataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Access Rules 的本地化字符串。
        /// </summary>
        internal static string DataRules {
            get {
                return ResourceManager.GetString("DataRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Access Rules | {0} 的本地化字符串。
        /// </summary>
        internal static string DataRulesPageTitle {
            get {
                return ResourceManager.GetString("DataRulesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string DefaultPageTitle {
            get {
                return ResourceManager.GetString("DefaultPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted Studies 的本地化字符串。
        /// </summary>
        internal static string DeletedStudies {
            get {
                return ResourceManager.GetString("DeletedStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted Studies | {0} 的本地化字符串。
        /// </summary>
        internal static string DeletedStudiesPageTitle {
            get {
                return ResourceManager.GetString("DeletedStudiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Management 的本地化字符串。
        /// </summary>
        internal static string DeleteManagement {
            get {
                return ResourceManager.GetString("DeleteManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Series Confirmation 的本地化字符串。
        /// </summary>
        internal static string DeleteSeriesConfirmDialogTitle {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Confirmation 的本地化字符串。
        /// </summary>
        internal static string DeleteStudyConfirmation {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Study Confirmation 的本地化字符串。
        /// </summary>
        internal static string DeleteStudyConfirmDialogTitle {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm 的本地化字符串。
        /// </summary>
        internal static string DeleteWorkQueueConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("DeleteWorkQueueConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices 的本地化字符串。
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices | {0} 的本地化字符串。
        /// </summary>
        internal static string DevicesPageTitle {
            get {
                return ResourceManager.GetString("DevicesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Tags 的本地化字符串。
        /// </summary>
        internal static string DicomTagsTitle {
            get {
                return ResourceManager.GetString("DicomTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Partition Archive 的本地化字符串。
        /// </summary>
        internal static string EditPartitionArchiveTitle {
            get {
                return ResourceManager.GetString("EditPartitionArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Study Details 的本地化字符串。
        /// </summary>
        internal static string EditStudyDialog {
            get {
                return ResourceManager.GetString("EditStudyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error | {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File System Queue 的本地化字符串。
        /// </summary>
        internal static string FileSystemQueue {
            get {
                return ResourceManager.GetString("FileSystemQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Systems 的本地化字符串。
        /// </summary>
        internal static string FileSystems {
            get {
                return ResourceManager.GetString("FileSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Systems | {0} 的本地化字符串。
        /// </summary>
        internal static string FileSystemsPageTitle {
            get {
                return ResourceManager.GetString("FileSystemsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Javascript Required 的本地化字符串。
        /// </summary>
        internal static string JavascriptRequiredPageTitle {
            get {
                return ResourceManager.GetString("JavascriptRequiredPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not for Diagnostic Use 的本地化字符串。
        /// </summary>
        internal static string LabelNotForDiagnosticUse {
            get {
                return ResourceManager.GetString("LabelNotForDiagnosticUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Series 的本地化字符串。
        /// </summary>
        internal static string MoveSeries {
            get {
                return ResourceManager.GetString("MoveSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Series Confirmation 的本地化字符串。
        /// </summary>
        internal static string MoveSeries_Dialog_Confirmation {
            get {
                return ResourceManager.GetString("MoveSeries_Dialog_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Studies 的本地化字符串。
        /// </summary>
        internal static string MoveStudies {
            get {
                return ResourceManager.GetString("MoveStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Studies | {0} 的本地化字符串。
        /// </summary>
        internal static string MoveStudiesPageTitle {
            get {
                return ResourceManager.GetString("MoveStudiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Confirmation 的本地化字符串。
        /// </summary>
        internal static string MoveStudy_Dialog_Confirmation {
            get {
                return ResourceManager.GetString("MoveStudy_Dialog_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Archive 的本地化字符串。
        /// </summary>
        internal static string PartitionArchive {
            get {
                return ResourceManager.GetString("PartitionArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Archives | {0} 的本地化字符串。
        /// </summary>
        internal static string PartitionArchivesPageTitle {
            get {
                return ResourceManager.GetString("PartitionArchivesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Expired 的本地化字符串。
        /// </summary>
        internal static string PasswordExpiredDialogTitle {
            get {
                return ResourceManager.GetString("PasswordExpiredDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queues 的本地化字符串。
        /// </summary>
        internal static string Queues {
            get {
                return ResourceManager.GetString("Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate SOP Reconciliation 的本地化字符串。
        /// </summary>
        internal static string ReconcileDuplicateSOPDialog {
            get {
                return ResourceManager.GetString("ReconcileDuplicateSOPDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reconcile Study 的本地化字符串。
        /// </summary>
        internal static string ReconcileStudyDialog {
            get {
                return ResourceManager.GetString("ReconcileStudyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Queue 的本地化字符串。
        /// </summary>
        internal static string RestoreQueue {
            get {
                return ResourceManager.GetString("RestoreQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Queue | {0} 的本地化字符串。
        /// </summary>
        internal static string RestoreQueuePageTitle {
            get {
                return ResourceManager.GetString("RestoreQueuePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Confirmation 的本地化字符串。
        /// </summary>
        internal static string RestoreStudyConfirmation {
            get {
                return ResourceManager.GetString("RestoreStudyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reschedule Work Queue Item 的本地化字符串。
        /// </summary>
        internal static string ScheduleWorkQueueDialogTitle {
            get {
                return ResourceManager.GetString("ScheduleWorkQueueDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search | {0} 的本地化字符串。
        /// </summary>
        internal static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series 的本地化字符串。
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Details 的本地化字符串。
        /// </summary>
        internal static string SeriesDetails {
            get {
                return ResourceManager.GetString("SeriesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Partitions 的本地化字符串。
        /// </summary>
        internal static string ServerPartitions {
            get {
                return ResourceManager.GetString("ServerPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Partitions | {0} 的本地化字符串。
        /// </summary>
        internal static string ServerPartitionsPageTitle {
            get {
                return ResourceManager.GetString("ServerPartitionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Rules 的本地化字符串。
        /// </summary>
        internal static string ServerRules {
            get {
                return ResourceManager.GetString("ServerRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Rules | {0} 的本地化字符串。
        /// </summary>
        internal static string ServerRulesPageTitle {
            get {
                return ResourceManager.GetString("ServerRulesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Scheduling 的本地化字符串。
        /// </summary>
        internal static string ServiceScheduling {
            get {
                return ResourceManager.GetString("ServiceScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Scheduling | {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceSchedulingPageTitle {
            get {
                return ResourceManager.GetString("ServiceSchedulingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Info 的本地化字符串。
        /// </summary>
        internal static string SIQ_ReconcileDialog_AdditionalInfoTabTitle {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDialog_AdditionalInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        internal static string SIQ_ReconcileDialog_OverviewTabTitle {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDialog_OverviewTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Studies 的本地化字符串。
        /// </summary>
        internal static string Studies {
            get {
                return ResourceManager.GetString("Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Studies | {0} 的本地化字符串。
        /// </summary>
        internal static string StudiesPageTitle {
            get {
                return ResourceManager.GetString("StudiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Details 的本地化字符串。
        /// </summary>
        internal static string StudyDetails {
            get {
                return ResourceManager.GetString("StudyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        internal static string StudyHistory {
            get {
                return ResourceManager.GetString("StudyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Integrity Queue 的本地化字符串。
        /// </summary>
        internal static string StudyIntegrityQueue {
            get {
                return ResourceManager.GetString("StudyIntegrityQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Integrity Queue | {0} 的本地化字符串。
        /// </summary>
        internal static string StudyIntegrityQueuePageTitle {
            get {
                return ResourceManager.GetString("StudyIntegrityQueuePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Storage 的本地化字符串。
        /// </summary>
        internal static string StudyStorage {
            get {
                return ResourceManager.GetString("StudyStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session timed out 的本地化字符串。
        /// </summary>
        internal static string TimeoutErrorPageTitle {
            get {
                return ResourceManager.GetString("TimeoutErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Data Access Authority Group Assignments 的本地化字符串。
        /// </summary>
        internal static string UpdateAuthorityGroupDialog {
            get {
                return ResourceManager.GetString("UpdateAuthorityGroupDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Groups 的本地化字符串。
        /// </summary>
        internal static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Groups | {0} 的本地化字符串。
        /// </summary>
        internal static string UserGroupsPageTitle {
            get {
                return ResourceManager.GetString("UserGroupsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users | {0} 的本地化字符串。
        /// </summary>
        internal static string UserManagementPageTitle {
            get {
                return ResourceManager.GetString("UserManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webstation | {0} 的本地化字符串。
        /// </summary>
        internal static string ViewImagesPageTitle {
            get {
                return ResourceManager.GetString("ViewImagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Queue 的本地化字符串。
        /// </summary>
        internal static string WorkQueue {
            get {
                return ResourceManager.GetString("WorkQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkQueue Item Details 的本地化字符串。
        /// </summary>
        internal static string WorkQueueItemDetails {
            get {
                return ResourceManager.GetString("WorkQueueItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Queue | {0} 的本地化字符串。
        /// </summary>
        internal static string WorkQueuePageTitle {
            get {
                return ResourceManager.GetString("WorkQueuePageTitle", resourceCulture);
            }
        }
    }
}
