//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageServer.Web.Common.PageSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class AboutPage : global::System.Configuration.ApplicationSettingsBase {
        
        private static AboutPage defaultInstance = ((AboutPage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AboutPage())));
        
        public static AboutPage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsersGuideUrl {
            get {
                return ((string)(this["UsersGuideUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ClearCanvas.ca/dnn/Resources/Documentation/tabid/107/Default.aspx")]
        public string DocumentationUrl {
            get {
                return ((string)(this["DocumentationUrl"]));
            }
        }
    }
}
