//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Volume.Mpr {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Volume.Mpr.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Move MPR 的本地化字符串。
        /// </summary>
        public static string CommandMprMove {
            get {
                return ResourceManager.GetString("CommandMprMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset MPR 的本地化字符串。
        /// </summary>
        public static string CommandMprReset {
            get {
                return ResourceManager.GetString("CommandMprReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reslice MPR 的本地化字符串。
        /// </summary>
        public static string CommandMprReslice {
            get {
                return ResourceManager.GetString("CommandMprReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to load the selected images in MPR 的本地化字符串。
        /// </summary>
        public static string ExceptionMprLoadFailure {
            get {
                return ResourceManager.GetString("ExceptionMprLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR ({0}) 的本地化字符串。
        /// </summary>
        public static string FormatMprDisplaySetName {
            get {
                return ResourceManager.GetString("FormatMprDisplaySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR {0} 的本地化字符串。
        /// </summary>
        public static string FormatMprWorkspaceTitle {
            get {
                return ResourceManager.GetString("FormatMprWorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (X{0:f0}° x Y{1:f0}° x Z{2:f0}°) 的本地化字符串。
        /// </summary>
        public static string FormatSliceCustom {
            get {
                return ResourceManager.GetString("FormatSliceCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identity 的本地化字符串。
        /// </summary>
        public static string FormatSliceIdentity {
            get {
                return ResourceManager.GetString("FormatSliceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrthoX 的本地化字符串。
        /// </summary>
        public static string FormatSliceOrthogonalX {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrthoY 的本地化字符串。
        /// </summary>
        public static string FormatSliceOrthogonalY {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} 的本地化字符串。
        /// </summary>
        public static string FormatVolumeLabel {
            get {
                return ResourceManager.GetString("FormatVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {2} ({0} - {1}) 的本地化字符串。
        /// </summary>
        public static string FormatVolumeLabelWithSeries {
            get {
                return ResourceManager.GetString("FormatVolumeLabelWithSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Debug 的本地化字符串。
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;MPR 的本地化字符串。
        /// </summary>
        public static string MenuMpr {
            get {
                return ResourceManager.GetString("MenuMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selection with &amp;MPR 的本地化字符串。
        /// </summary>
        public static string MenuOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open with &amp;MPR... 的本地化字符串。
        /// </summary>
        public static string MenuOpenWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Reset MPR 的本地化字符串。
        /// </summary>
        public static string MenuResetAll {
            get {
                return ResourceManager.GetString("MenuResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reslice MPR 的本地化字符串。
        /// </summary>
        public static string MenuReslice {
            get {
                return ResourceManager.GetString("MenuReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reslice {0} 的本地化字符串。
        /// </summary>
        public static string MenuResliceFor {
            get {
                return ResourceManager.GetString("MenuResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Volume 的本地化字符串。
        /// </summary>
        public static string MenuVolume {
            get {
                return ResourceManager.GetString("MenuVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building MPR Volume... 的本地化字符串。
        /// </summary>
        public static string MessageBuildingMprVolume {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building MPR Volume (Frame {1} of {2})... 的本地化字符串。
        /// </summary>
        public static string MessageBuildingMprVolumeProgress {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolumeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done! 的本地化字符串。
        /// </summary>
        public static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing MPR... 的本地化字符串。
        /// </summary>
        public static string MessageInitializingMpr {
            get {
                return ResourceManager.GetString("MessageInitializingMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performing MPR Workspace Layout... 的本地化字符串。
        /// </summary>
        public static string MessagePerformingMprWorkspaceLayout {
            get {
                return ResourceManager.GetString("MessagePerformingMprWorkspaceLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected images are of an unsupported type. MPR only supports DICOM image SOPs. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesAreNotSupported {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected images have a gantry slew. MPR only supports gantry tilts. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMayBotBeGantrySlewed {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMayBotBeGantrySlewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected images have an anisotropic pixel aspect ratio. MPR only supports 1:1 isotropic aspect ratios. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMayNotHaveAnisotropicPixels {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMayNotHaveAnisotropicPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR only supports 16-bit greyscale images. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMustBe16BitGreyscale {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMustBe16BitGreyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected images must be calibrated. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMustBeCalibrated {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMustBeCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inconsistent spacing between images. MPR requires evenly spaced images. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMustBeEvenlySpacedForMpr {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMustBeEvenlySpacedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two images are at same patient location. MPR requires evenly spaced images. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetImagesMustBeUniquelyLocatedForMpr {
            get {
                return ResourceManager.GetString("MessageSourceDataSetImagesMustBeUniquelyLocatedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected multiframe images are of an unsupported type. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMultiFrameImagesAreNotSupported {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMultiFrameImagesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must have the same image orientation (Patient). 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustBeSameImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustBeSameImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must have the same frame of reference. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustBeSingleFrameOfReference {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustBeSingleFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must be from the same series. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustBeSingleSeries {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustBeSingleSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must be from the same study. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustBeSingleStudy {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustBeSingleStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must have a defined image orientation (Patient). 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustDefineImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustDefineImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each frame in the source dataset must specify a frame of reference. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetMustSpecifyFrameOfReference {
            get {
                return ResourceManager.GetString("MessageSourceDataSetMustSpecifyFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source dataset must contain at least three frames. 的本地化字符串。
        /// </summary>
        public static string MessageSourceDataSetNeedsThreeImagesForMpr {
            get {
                return ResourceManager.GetString("MessageSourceDataSetNeedsThreeImagesForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected exception was encountered while creating the volume. 的本地化字符串。
        /// </summary>
        public static string MessageUnexpectedCreateVolumeException {
            get {
                return ResourceManager.GetString("MessageUnexpectedCreateVolumeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File is not a valid, supported DICOM image SOP instance. {0} 的本地化字符串。
        /// </summary>
        public static string MessageUnsupportedDicomImageSop {
            get {
                return ResourceManager.GetString("MessageUnsupportedDicomImageSop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slice spacing must be greater than or equal to 0.5 and less than or equal to 10. 的本地化字符串。
        /// </summary>
        public static string MessageValidateSliceSpacing {
            get {
                return ResourceManager.GetString("MessageValidateSliceSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR 的本地化字符串。
        /// </summary>
        public static string Mpr {
            get {
                return ResourceManager.GetString("Mpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 Plane 的本地化字符串。
        /// </summary>
        public static string ThreePlane {
            get {
                return ResourceManager.GetString("ThreePlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR 的本地化字符串。
        /// </summary>
        public static string ToolbarMpr {
            get {
                return ResourceManager.GetString("ToolbarMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selection with MPR 的本地化字符串。
        /// </summary>
        public static string ToolbarOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("ToolbarOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset MPR 的本地化字符串。
        /// </summary>
        public static string ToolbarResetAll {
            get {
                return ResourceManager.GetString("ToolbarResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reslice MPR 的本地化字符串。
        /// </summary>
        public static string ToolbarReslice {
            get {
                return ResourceManager.GetString("ToolbarReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reslice {0} 的本地化字符串。
        /// </summary>
        public static string ToolbarResliceFor {
            get {
                return ResourceManager.GetString("ToolbarResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resets all MPR slice views 的本地化字符串。
        /// </summary>
        public static string TooltipResetAll {
            get {
                return ResourceManager.GetString("TooltipResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 :: 的本地化字符串。
        /// </summary>
        public static string VolumeLabelSeparator {
            get {
                return ResourceManager.GetString("VolumeLabelSeparator", resourceCulture);
            }
        }
    }
}
