//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.StudyManagement {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.StudyManagement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Activity 的本地化字符串。
        /// </summary>
        public static string ColumnActivityDescription {
            get {
                return ResourceManager.GetString("ColumnActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient 的本地化字符串。
        /// </summary>
        public static string ColumnPatient {
            get {
                return ResourceManager.GetString("ColumnPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string ColumnPriority {
            get {
                return ResourceManager.GetString("ColumnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string ColumnProgress {
            get {
                return ResourceManager.GetString("ColumnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested Time 的本地化字符串。
        /// </summary>
        public static string ColumnRequestedTime {
            get {
                return ResourceManager.GetString("ColumnRequestedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled Time 的本地化字符串。
        /// </summary>
        public static string ColumnScheduledTime {
            get {
                return ResourceManager.GetString("ColumnScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Details 的本地化字符串。
        /// </summary>
        public static string ColumnStatusDescription {
            get {
                return ResourceManager.GetString("ColumnStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study 的本地化字符串。
        /// </summary>
        public static string ColumnStudy {
            get {
                return ResourceManager.GetString("ColumnStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk usage is above the maximum. The Workstation will not be able to import
        ///DICOM files or receive them over the network. You should delete old studies to
        ///make room, or increase the maximum usage. 的本地化字符串。
        /// </summary>
        public static string DescriptionMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("DescriptionMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} ({2}%) 的本地化字符串。
        /// </summary>
        public static string DiskspaceTemplate {
            get {
                return ResourceManager.GetString("DiskspaceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Activity Monitor 的本地化字符串。
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Storage Configuration 的本地化字符串。
        /// </summary>
        public static string LinkOpenStorageConfiguration {
            get {
                return ResourceManager.GetString("LinkOpenStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监视器 的本地化字符串。
        /// </summary>
        public static string MenuActivityMonitor {
            get {
                return ResourceManager.GetString("MenuActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string MenuDeleteWorkItem {
            get {
                return ResourceManager.GetString("MenuDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库维护 的本地化字符串。
        /// </summary>
        public static string MenuReindex {
            get {
                return ResourceManager.GetString("MenuReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string MenuRestartWorkItem {
            get {
                return ResourceManager.GetString("MenuRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Stat 的本地化字符串。
        /// </summary>
        public static string MenuStatWorkItem {
            get {
                return ResourceManager.GetString("MenuStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string MenuStopWorkItem {
            get {
                return ResourceManager.GetString("MenuStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling the selected work item(s) may result in partial study data, which could potentially lead to patient misdiagnosis.  Are you sure you want to cancel? 的本地化字符串。
        /// </summary>
        public static string MessageConfirmCancelWorkItems {
            get {
                return ResourceManager.GetString("MessageConfirmCancelWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open the selected images. 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenImages {
            get {
                return ResourceManager.GetString("MessageFailedToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open the selected studies. 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenStudy {
            get {
                return ResourceManager.GetString("MessageFailedToOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start re-index. 的本地化字符串。
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The currently configured file store directory does not exist. 的本地化字符串。
        /// </summary>
        public static string MessageFilestoreDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageFilestoreDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some of the studies you selected are being processed. They may be incomplete or contain out-of-date information. Do you still want to continue? 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudiesBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudiesBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study you selected is being processed. It may be incomplete or contain out-of-date information. Do you still want to continue? 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Local Server must be running in order to complete this operation. 的本地化字符串。
        /// </summary>
        public static string MessageLocalServerNotRunning {
            get {
                return ResourceManager.GetString("MessageLocalServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum disk usage exceeded 的本地化字符串。
        /// </summary>
        public static string MessageMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed. 的本地化字符串。
        /// </summary>
        public static string MessageNonStudyWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageNonStudyWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is 1 failed work item. 的本地化字符串。
        /// </summary>
        public static string MessageOneFailedWorkItem {
            get {
                return ResourceManager.GetString("MessageOneFailedWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processed {0} of {1} items... 的本地化字符串。
        /// </summary>
        public static string MessageProcessedItemsProgress {
            get {
                return ResourceManager.GetString("MessageProcessedItemsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A re-index operation is already in progress. 的本地化字符串。
        /// </summary>
        public static string MessageReindexInProgress {
            get {
                return ResourceManager.GetString("MessageReindexInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The re-index has been scheduled. 的本地化字符串。
        /// </summary>
        public static string MessageReindexScheduled {
            get {
                return ResourceManager.GetString("MessageReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The service must be running to start a re-index. 的本地化字符串。
        /// </summary>
        public static string MessageReindexServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageReindexServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are {0} failed work items. 的本地化字符串。
        /// </summary>
        public static string MessageTotalFailedWorkItems {
            get {
                return ResourceManager.GetString("MessageTotalFailedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} for {1} [{2}, A#:{3}] failed. 的本地化字符串。
        /// </summary>
        public static string MessageWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (all) 的本地化字符串。
        /// </summary>
        public static string NoFilterItem {
            get {
                return ResourceManager.GetString("NoFilterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueActive {
            get {
                return ResourceManager.GetString("StatusFilterValueActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueComplete {
            get {
                return ResourceManager.GetString("StatusFilterValueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueFailed {
            get {
                return ResourceManager.GetString("StatusFilterValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueStopped {
            get {
                return ResourceManager.GetString("StatusFilterValueStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity Monitor 的本地化字符串。
        /// </summary>
        public static string TitleActivityMonitor {
            get {
                return ResourceManager.GetString("TitleActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity Monitor 的本地化字符串。
        /// </summary>
        public static string TooltipActivityMonitor {
            get {
                return ResourceManager.GetString("TooltipActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected work item(s) 的本地化字符串。
        /// </summary>
        public static string TooltipDeleteWorkItem {
            get {
                return ResourceManager.GetString("TooltipDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart selected work item(s) 的本地化字符串。
        /// </summary>
        public static string TooltipRestartWorkItem {
            get {
                return ResourceManager.GetString("TooltipRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raise priority of selected work item(s) to &apos;Stat&apos; 的本地化字符串。
        /// </summary>
        public static string TooltipStatWorkItem {
            get {
                return ResourceManager.GetString("TooltipStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop selected work item(s) 的本地化字符串。
        /// </summary>
        public static string TooltipStopWorkItem {
            get {
                return ResourceManager.GetString("TooltipStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have permission to open the Activity Monitor. 的本地化字符串。
        /// </summary>
        public static string WarningActivityMonitorPermission {
            get {
                return ResourceManager.GetString("WarningActivityMonitorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum disk usage has been exceeded.  Other devices will not be able to send studies to the workstation. 的本地化字符串。
        /// </summary>
        public static string WarningMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("WarningMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have permission to start a re-index. 的本地化字符串。
        /// </summary>
        public static string WarningReindexPermission {
            get {
                return ResourceManager.GetString("WarningReindexPermission", resourceCulture);
            }
        }
    }
}
