namespace Macro.Common.Media.IMAPI2
{
    public enum IMAPI_CD_SECTOR_TYPE
    {
        IMAPI_CD_SECTOR_AUDIO = 0x00,
        IMAPI_CD_SECTOR_MODE_ZERO = 0x01,
        IMAPI_CD_SECTOR_MODE1 = 0x02,
        IMAPI_CD_SECTOR_MODE2FORM0 = 0x03,
        IMAPI_CD_SECTOR_MODE2FORM1 = 0x04,
        IMAPI_CD_SECTOR_MODE2FORM2 = 0x05,
        IMAPI_CD_SECTOR_MODE1RAW = 0x06,
        IMAPI_CD_SECTOR_MODE2FORM0RAW = 0x07,
        IMAPI_CD_SECTOR_MODE2FORM1RAW = 0x08,
        IMAPI_CD_SECTOR_MODE2FORM2RAW = 0x09
    }
}