//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Utilities.StudyFilters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class StudyFilterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StudyFilterSettings defaultInstance = ((StudyFilterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StudyFilterSettings())));
        
        public static StudyFilterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// List of user-selected columns to show in the Study Filters window.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("List of user-selected columns to show in the Study Filters window.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Filename</string>
  <string>FileSize</string>
  <string>00100020</string>
  <string>00100010</string>
  <string>00100030</string>
  <string>00200010</string>
  <string>00080050</string>
  <string>00080020</string>
  <string>00081030</string>
  <string>00080060</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Columns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Columns"]));
            }
            set {
                this["Columns"] = value;
            }
        }
    }
}
