//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Web {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Web.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Studies matching the specified accession number could not be found. 的本地化字符串。
        /// </summary>
        internal static string MessageAccessionStudiesNotFound {
            get {
                return ResourceManager.GetString("MessageAccessionStudiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected error has occurred while searching for priors. Please contact your PACS administrator. 的本地化字符串。
        /// </summary>
        internal static string MessageLoadPriorsFindErrors {
            get {
                return ResourceManager.GetString("MessageLoadPriorsFindErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No studies could be found for the specified patient. 的本地化字符串。
        /// </summary>
        internal static string MessagePatientStudiesNotFound {
            get {
                return ResourceManager.GetString("MessagePatientStudiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The search for prior studies did not complete successfully because at least one of your priors servers was unreachable.
        ///Although some priors may be available, please be aware that you may be working with an incomplete patient history. 的本地化字符串。
        /// </summary>
        internal static string MessagePriorsIncomplete {
            get {
                return ResourceManager.GetString("MessagePriorsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The study could not be loaded. 的本地化字符串。
        /// </summary>
        internal static string MessageStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("MessageStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout Manager 的本地化字符串。
        /// </summary>
        internal static string TooltipLayoutManager {
            get {
                return ResourceManager.GetString("TooltipLayoutManager", resourceCulture);
            }
        }
    }
}
