//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Utilities.Media {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Utilities.Media.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 光盘空间不足或者没有光盘 的本地化字符串。
        /// </summary>
        internal static string BadDisc {
            get {
                return ResourceManager.GetString("BadDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to retrieve available media writers. The Windows Feature Pack for Storage may not be installed. 的本地化字符串。
        /// </summary>
        internal static string ExceptionIMAPI2NotInstalled {
            get {
                return ResourceManager.GetString("ExceptionIMAPI2NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to eject media. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMediaEjectFailure {
            get {
                return ResourceManager.GetString("ExceptionMediaEjectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to verify media. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMediaVerificationFailure {
            get {
                return ResourceManager.GetString("ExceptionMediaVerificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more of the specified studies could not be found in the local data store. 的本地化字符串。
        /// </summary>
        internal static string ExceptionStudyMissing {
            get {
                return ResourceManager.GetString("ExceptionStudyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Images with Macro Workstation 的本地化字符串。
        /// </summary>
        internal static string LabelOpenWithMacroWorkstation {
            get {
                return ResourceManager.GetString("LabelOpenWithMacroWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Disc 的本地化字符串。
        /// </summary>
        internal static string MediaTypeNameNotReady {
            get {
                return ResourceManager.GetString("MediaTypeNameNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Disc 的本地化字符串。
        /// </summary>
        internal static string MediaTypeNameUnknownDisc {
            get {
                return ResourceManager.GetString("MediaTypeNameUnknownDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能流的study 的本地化字符串。
        /// </summary>
        internal static string MessageCannotOpenNonStreamingStudy {
            get {
                return ResourceManager.GetString("MessageCannotOpenNonStreamingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageFormatXNonStreamingStudiesCannotBeOpened 的本地化字符串。
        /// </summary>
        internal static string MessageFormatXNonStreamingStudiesCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageFormatXNonStreamingStudiesCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有提供流数据 的本地化字符串。
        /// </summary>
        internal static string MessageOneNonStreamingStudyCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageOneNonStreamingStudyCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要刻录的数据 的本地化字符串。
        /// </summary>
        internal static string NoDataWillBurned {
            get {
                return ResourceManager.GetString("NoDataWillBurned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光驱不存在或不支持刻录功能 的本地化字符串。
        /// </summary>
        internal static string NoSupportRecord {
            get {
                return ResourceManager.GetString("NoSupportRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled. 的本地化字符串。
        /// </summary>
        internal static string StageCancelled {
            get {
                return ResourceManager.GetString("StageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling ... 的本地化字符串。
        /// </summary>
        internal static string StageCancelling {
            get {
                return ResourceManager.GetString("StageCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string StageCompleted {
            get {
                return ResourceManager.GetString("StageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating disc iamge (this may take a while)... 的本地化字符串。
        /// </summary>
        internal static string StageCreatingDiscImage {
            get {
                return ResourceManager.GetString("StageCreatingDiscImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed. 的本地化字符串。
        /// </summary>
        internal static string StageFailed {
            get {
                return ResourceManager.GetString("StageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finalizing media... 的本地化字符串。
        /// </summary>
        internal static string StageFinalizing {
            get {
                return ResourceManager.GetString("StageFinalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing writer 的本地化字符串。
        /// </summary>
        internal static string StageInitializing {
            get {
                return ResourceManager.GetString("StageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing media... 的本地化字符串。
        /// </summary>
        internal static string StagePreparingDisc {
            get {
                return ResourceManager.GetString("StagePreparingDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verifying media 的本地化字符串。
        /// </summary>
        internal static string StageVerifying {
            get {
                return ResourceManager.GetString("StageVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing... 的本地化字符串。
        /// </summary>
        internal static string StageWriting {
            get {
                return ResourceManager.GetString("StageWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储目录不存在 的本地化字符串。
        /// </summary>
        internal static string StagingFolderNofind {
            get {
                return ResourceManager.GetString("StagingFolderNofind", resourceCulture);
            }
        }
    }
}
