//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.BaseTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MouseToolSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MouseToolSettings defaultInstance = ((MouseToolSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MouseToolSettings())));
        
        public static MouseToolSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// User preferences for mouse tools, such as mouse button assignments and whether or not to automatically select the tool when the viewer first opens.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("User preferences for mouse tools, such as mouse button assignments and whether or" +
            " not to automatically select the tool when the viewer first opens.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Macro.ImageViewer.BaseTools.MouseToolSettingsProfile DefaultProfile {
            get {
                return ((global::Macro.ImageViewer.BaseTools.MouseToolSettingsProfile)(this["DefaultProfile"]));
            }
            set {
                this["DefaultProfile"] = value;
            }
        }
        
        /// <summary>
        /// Specifies whether or not to show the mouse button assignment in the tool&apos;s icon.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies whether or not to show the mouse button assignment in the tool\'s icon.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMouseButtonIconOverlay {
            get {
                return ((bool)(this["ShowMouseButtonIconOverlay"]));
            }
            set {
                this["ShowMouseButtonIconOverlay"] = value;
            }
        }
    }
}
