//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Clipboard {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Clipboard.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Export 的本地化字符串。
        /// </summary>
        internal static string ConfigureImageExport {
            get {
                return ResourceManager.GetString("ConfigureImageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AVI Video Files 的本地化字符串。
        /// </summary>
        internal static string DescriptionAvi {
            get {
                return ResourceManager.GetString("DescriptionAvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitmap Image Format (BMP) 的本地化字符串。
        /// </summary>
        internal static string DescriptionBmp {
            get {
                return ResourceManager.GetString("DescriptionBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics Interchange Format (GIF) 的本地化字符串。
        /// </summary>
        internal static string DescriptionGif {
            get {
                return ResourceManager.GetString("DescriptionGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Joint Photographic Experts Group (JPEG) 的本地化字符串。
        /// </summary>
        internal static string DescriptionJpg {
            get {
                return ResourceManager.GetString("DescriptionJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portable Network Graphics (PNG) 的本地化字符串。
        /// </summary>
        internal static string DescriptionPng {
            get {
                return ResourceManager.GetString("DescriptionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subset (Custom) 的本地化字符串。
        /// </summary>
        internal static string DescriptionSubsetCustom {
            get {
                return ResourceManager.GetString("DescriptionSubsetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subset (Range) 的本地化字符串。
        /// </summary>
        internal static string DescriptionSubsetRange {
            get {
                return ResourceManager.GetString("DescriptionSubsetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tagged Image File Format (TIFF) 的本地化字符串。
        /// </summary>
        internal static string DescriptionTiff {
            get {
                return ResourceManager.GetString("DescriptionTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination file 的本地化字符串。
        /// </summary>
        internal static string LabelExportFile {
            get {
                return ResourceManager.GetString("LabelExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination folder 的本地化字符串。
        /// </summary>
        internal static string LabelExportPath {
            get {
                return ResourceManager.GetString("LabelExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        internal static string LabelOff {
            get {
                return ResourceManager.GetString("LabelOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        internal static string LabelOn {
            get {
                return ResourceManager.GetString("LabelOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string MenuClipboard {
            get {
                return ResourceManager.GetString("MenuClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Display Set to Clipboard 的本地化字符串。
        /// </summary>
        internal static string MenuCopyDisplaySetToClipboard {
            get {
                return ResourceManager.GetString("MenuCopyDisplaySetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Image to Clipboard 的本地化字符串。
        /// </summary>
        internal static string MenuCopyImageToClipboard {
            get {
                return ResourceManager.GetString("MenuCopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Range of Images to Clipboard 的本地化字符串。
        /// </summary>
        internal static string MenuCopySubsetToClipboard {
            get {
                return ResourceManager.GetString("MenuCopySubsetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("MenuDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteClipboardItem {
            get {
                return ResourceManager.GetString("MenuDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Image 的本地化字符串。
        /// </summary>
        internal static string MenuExportToImage {
            get {
                return ResourceManager.GetString("MenuExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Video 的本地化字符串。
        /// </summary>
        internal static string MenuExportToVideo {
            get {
                return ResourceManager.GetString("MenuExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string MenuShowClipboard {
            get {
                return ResourceManager.GetString("MenuShowClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled. 的本地化字符串。
        /// </summary>
        internal static string MessageCancelled {
            get {
                return ResourceManager.GetString("MessageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add item(s) to clipboard 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardCopyFailed {
            get {
                return ResourceManager.GetString("MessageClipboardCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Id: {0}
        ///Patient Name: {1}
        ///Study Date: {2}
        ///Study Description: {3}
        ///Accession Number: {4}
        ///Modality: {5}
        ///Text Overlay: {6} 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardDescription {
            get {
                return ResourceManager.GetString("MessageClipboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - Image #{1}, Frame #{2} 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardNameMultiframeImage {
            get {
                return ResourceManager.GetString("MessageClipboardNameMultiframeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - Image #{1} 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardNameSingleImage {
            get {
                return ResourceManager.GetString("MessageClipboardNameSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating video ... 的本地化字符串。
        /// </summary>
        internal static string MessageCreatingVideo {
            get {
                return ResourceManager.GetString("MessageCreatingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom range is invalid. 的本地化字符串。
        /// </summary>
        internal static string MessageCustomRangeInvalid {
            get {
                return ResourceManager.GetString("MessageCustomRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified directory does not exist. 的本地化字符串。
        /// </summary>
        internal static string MessageDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The display set must have 2 or more images to be exported to video. 的本地化字符串。
        /// </summary>
        internal static string MessageDisplaySetTooFewImagesForVideo {
            get {
                return ResourceManager.GetString("MessageDisplaySetTooFewImagesForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The end value must be less than or equal to the start value. 的本地化字符串。
        /// </summary>
        internal static string MessageEndValueLargerThanStart {
            get {
                return ResourceManager.GetString("MessageEndValueLargerThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The end value is out of range. 的本地化字符串。
        /// </summary>
        internal static string MessageEndValueOutOfRange {
            get {
                return ResourceManager.GetString("MessageEndValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occurred while attempting to launch the configuration dialog.  Please check the log for more details. 的本地化字符串。
        /// </summary>
        internal static string MessageErrorLaunchingConfigurationComponent {
            get {
                return ResourceManager.GetString("MessageErrorLaunchingConfigurationComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete. 的本地化字符串。
        /// </summary>
        internal static string MessageExportComplete {
            get {
                return ResourceManager.GetString("MessageExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export failed.  Please check the log for more details. 的本地化字符串。
        /// </summary>
        internal static string MessageExportFailed {
            get {
                return ResourceManager.GetString("MessageExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting Images ... 的本地化字符串。
        /// </summary>
        internal static string MessageExportingImages {
            get {
                return ResourceManager.GetString("MessageExportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to video failed.  Please see the log for more details. 的本地化字符串。
        /// </summary>
        internal static string MessageExportToVideoFailed {
            get {
                return ResourceManager.GetString("MessageExportToVideoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting frame #{0} of {1} 的本地化字符串。
        /// </summary>
        internal static string MessageFormatExportingFrame {
            get {
                return ResourceManager.GetString("MessageFormatExportingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another export job is currently running.  You must wait until it completes to export more images. 的本地化字符串。
        /// </summary>
        internal static string MessageImageExportStillRunning {
            get {
                return ResourceManager.GetString("MessageImageExportStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file path is invalid. 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidFilePath {
            get {
                return ResourceManager.GetString("MessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no acceptable video codecs installed. 的本地化字符串。
        /// </summary>
        internal static string MessageNoAcceptableCodecsInstalled {
            get {
                return ResourceManager.GetString("MessageNoAcceptableCodecsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n/a 的本地化字符串。
        /// </summary>
        internal static string MessageNotApplicable {
            get {
                return ResourceManager.GetString("MessageNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interval value is invalid. 的本地化字符串。
        /// </summary>
        internal static string MessageRangeIntervalInvalid {
            get {
                return ResourceManager.GetString("MessageRangeIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The start value is out of range. 的本地化字符串。
        /// </summary>
        internal static string MessageStartValueOutOfRange {
            get {
                return ResourceManager.GetString("MessageStartValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one of the items could not be removed from the clipboard because it is in use. 的本地化字符串。
        /// </summary>
        internal static string MessageUnableToClearClipboardItems {
            get {
                return ResourceManager.GetString("MessageUnableToClearClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another video is currently being created.  You must wait until it completes to create another. 的本地化字符串。
        /// </summary>
        internal static string MessageVideoExportStillRunning {
            get {
                return ResourceManager.GetString("MessageVideoExportStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Options 的本地化字符串。
        /// </summary>
        internal static string TitleAdvancedOptions {
            get {
                return ResourceManager.GetString("TitleAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string TitleClipboard {
            get {
                return ResourceManager.GetString("TitleClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Images to Clipboard 的本地化字符串。
        /// </summary>
        internal static string TitleCopySubsetToClipboard {
            get {
                return ResourceManager.GetString("TitleCopySubsetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating Video 的本地化字符串。
        /// </summary>
        internal static string TitleCreatingVideo {
            get {
                return ResourceManager.GetString("TitleCreatingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Images 的本地化字符串。
        /// </summary>
        internal static string TitleExportImages {
            get {
                return ResourceManager.GetString("TitleExportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting Images 的本地化字符串。
        /// </summary>
        internal static string TitleExportingImages {
            get {
                return ResourceManager.GetString("TitleExportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Single Image 的本地化字符串。
        /// </summary>
        internal static string TitleExportSingleImage {
            get {
                return ResourceManager.GetString("TitleExportSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Video 的本地化字符串。
        /// </summary>
        internal static string TitleExportToVideo {
            get {
                return ResourceManager.GetString("TitleExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All 的本地化字符串。
        /// </summary>
        internal static string ToolbalDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("ToolbalDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected 的本地化字符串。
        /// </summary>
        internal static string ToolbarDeleteClipboardItem {
            get {
                return ResourceManager.GetString("ToolbarDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Image 的本地化字符串。
        /// </summary>
        internal static string ToolbarExportToImage {
            get {
                return ResourceManager.GetString("ToolbarExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Video 的本地化字符串。
        /// </summary>
        internal static string ToolbarExportToVideo {
            get {
                return ResourceManager.GetString("ToolbarExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string ToolbarShowClipboard {
            get {
                return ResourceManager.GetString("ToolbarShowClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("TooltipDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteClipboardItem {
            get {
                return ResourceManager.GetString("TooltipDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Image 的本地化字符串。
        /// </summary>
        internal static string TooltipExportToImage {
            get {
                return ResourceManager.GetString("TooltipExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Video 的本地化字符串。
        /// </summary>
        internal static string TooltipExportToVideo {
            get {
                return ResourceManager.GetString("TooltipExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Clipboard 的本地化字符串。
        /// </summary>
        internal static string TooltipShowClipboard {
            get {
                return ResourceManager.GetString("TooltipShowClipboard", resourceCulture);
            }
        }
    }
}
