//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Explorer.Local {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Explorer.Local.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import the selected items because the local services are not running.
        ///Please ensure the &apos;{0}&apos; is running or contact your system administrator for assistance. 的本地化字符串。
        /// </summary>
        public static string FormatMessageImportWorkItemServiceNotRunning {
            get {
                return ResourceManager.GetString("FormatMessageImportWorkItemServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string ImportDicomFiles {
            get {
                return ResourceManager.GetString("ImportDicomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Activity Monitor 的本地化字符串。
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string MenuOpenFiles {
            get {
                return ResourceManager.GetString("MenuOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initiate an import of the selected items. 的本地化字符串。
        /// </summary>
        public static string MessageFailedToImportSelection {
            get {
                return ResourceManager.GetString("MessageFailedToImportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file could not be found. 的本地化字符串。
        /// </summary>
        public static string MessageFileNotFound {
            get {
                return ResourceManager.GetString("MessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} images failed to load. 的本地化字符串。
        /// </summary>
        public static string MessageFormatImagesFailedToLoad {
            get {
                return ResourceManager.GetString("MessageFormatImagesFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing files from {0} location. 的本地化字符串。
        /// </summary>
        public static string MessageFormatImportingFiles {
            get {
                return ResourceManager.GetString("MessageFormatImportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing files from {0} locations. 的本地化字符串。
        /// </summary>
        public static string MessageFormatImportingFilesPlural {
            get {
                return ResourceManager.GetString("MessageFormatImportingFilesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified path does not contain any files. 的本地化字符串。
        /// </summary>
        public static string MessageNoFilesSelected {
            get {
                return ResourceManager.GetString("MessageNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have permission to open images in the viewer. 的本地化字符串。
        /// </summary>
        public static string MessagePermissionToOpenFilesDenied {
            get {
                return ResourceManager.GetString("MessagePermissionToOpenFilesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open images. 的本地化字符串。
        /// </summary>
        public static string MessageUnableToOpenImages {
            get {
                return ResourceManager.GetString("MessageUnableToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的电脑 的本地化字符串。
        /// </summary>
        public static string MyComputer {
            get {
                return ResourceManager.GetString("MyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Dicom Files 的本地化字符串。
        /// </summary>
        public static string OpenDicomFilesVerbose {
            get {
                return ResourceManager.GetString("OpenDicomFilesVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import DICOM files from the local file system 的本地化字符串。
        /// </summary>
        public static string TooltipImportDicomFiles {
            get {
                return ResourceManager.GetString("TooltipImportDicomFiles", resourceCulture);
            }
        }
    }
}
