//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Tools.Standard {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Tools.Standard.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 added 的本地化字符串。
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically applies window/level 的本地化字符串。
        /// </summary>
        internal static string AutoPresetVoiLutOperationDescription {
            get {
                return ResourceManager.GetString("AutoPresetVoiLutOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string AutoPresetVoiLutOperationFactoryDescription {
            get {
                return ResourceManager.GetString("AutoPresetVoiLutOperationFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string AutoPresetVoiLutOperationName {
            get {
                return ResourceManager.GetString("AutoPresetVoiLutOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colour Maps 的本地化字符串。
        /// </summary>
        internal static string ColourMaps {
            get {
                return ResourceManager.GetString("ColourMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cine 的本地化字符串。
        /// </summary>
        internal static string CommandCine {
            get {
                return ResourceManager.GetString("CommandCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Custom Shutters 的本地化字符串。
        /// </summary>
        internal static string CommandClearCustomShutters {
            get {
                return ResourceManager.GetString("CommandClearCustomShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Map 的本地化字符串。
        /// </summary>
        internal static string CommandColorMap {
            get {
                return ResourceManager.GetString("CommandColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Text Area 的本地化字符串。
        /// </summary>
        internal static string CommandCreateTextArea {
            get {
                return ResourceManager.GetString("CommandCreateTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Text Callout 的本地化字符串。
        /// </summary>
        internal static string CommandCreateTextCallout {
            get {
                return ResourceManager.GetString("CommandCreateTextCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Annotations 的本地化字符串。
        /// </summary>
        internal static string CommandDeleteAllAnnotations {
            get {
                return ResourceManager.GetString("CommandDeleteAllAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Annotation 的本地化字符串。
        /// </summary>
        internal static string CommandDeleteAnnotation {
            get {
                return ResourceManager.GetString("CommandDeleteAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Custom Shutter 的本地化字符串。
        /// </summary>
        internal static string CommandDrawShutter {
            get {
                return ResourceManager.GetString("CommandDrawShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Horizontal 的本地化字符串。
        /// </summary>
        internal static string CommandFlipHorizontal {
            get {
                return ResourceManager.GetString("CommandFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Vertical 的本地化字符串。
        /// </summary>
        internal static string CommandFlipVertical {
            get {
                return ResourceManager.GetString("CommandFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert 的本地化字符串。
        /// </summary>
        internal static string CommandInvert {
            get {
                return ResourceManager.GetString("CommandInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Scale 的本地化字符串。
        /// </summary>
        internal static string CommandMatchScale {
            get {
                return ResourceManager.GetString("CommandMatchScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        internal static string CommandPan {
            get {
                return ResourceManager.GetString("CommandPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string CommandReset {
            get {
                return ResourceManager.GetString("CommandReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Left 的本地化字符串。
        /// </summary>
        internal static string CommandRotateLeft {
            get {
                return ResourceManager.GetString("CommandRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Right 的本地化字符串。
        /// </summary>
        internal static string CommandRotateRight {
            get {
                return ResourceManager.GetString("CommandRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Images 的本地化字符串。
        /// </summary>
        internal static string CommandSortImages {
            get {
                return ResourceManager.GetString("CommandSortImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack 的本地化字符串。
        /// </summary>
        internal static string CommandStack {
            get {
                return ResourceManager.GetString("CommandStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level 的本地化字符串。
        /// </summary>
        internal static string CommandWindowLevel {
            get {
                return ResourceManager.GetString("CommandWindowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level Preset 的本地化字符串。
        /// </summary>
        internal static string CommandWindowLevelPreset {
            get {
                return ResourceManager.GetString("CommandWindowLevelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string CommandZoom {
            get {
                return ResourceManager.GetString("CommandZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 edited 的本地化字符串。
        /// </summary>
        internal static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An equivalent preset already exists. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAnEquivalentPresetAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionAnEquivalentPresetAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An equivalent preset group already exists. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAnEquivalentPresetGroupAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionAnEquivalentPresetGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input configuration&apos;s factory name (&apos;{0}&apos;) does not match this factory&apos;s name (&apos;{1}&apos;). 的本地化字符串。
        /// </summary>
        internal static string ExceptionFormatFactoryNamesDoNotMatch {
            get {
                return ResourceManager.GetString("ExceptionFormatFactoryNamesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input presentation image must implement {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFormatInputPresentationImageMustImplement {
            get {
                return ResourceManager.GetString("ExceptionFormatInputPresentationImageMustImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid for Window Width. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFormatWindowWidthInvalid {
            get {
                return ResourceManager.GetString("ExceptionFormatWindowWidthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] is an invalid index.  Index must be between {1} and {2}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input value does not match an existing Modality. 的本地化字符串。
        /// </summary>
        internal static string ExceptionInputValueDoesntMatchExistingModality {
            get {
                return ResourceManager.GetString("ExceptionInputValueDoesntMatchExistingModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LUT index out of range (index = {0}). 的本地化字符串。
        /// </summary>
        internal static string ExceptionLUTIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionLUTIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output range of previous LUT does not match input range of current LUT. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLUTInputOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTInputOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output range of last LUT is not 8 bits. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLUTLastOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTLastOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum input value greater than or equal to maximum input value. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLUTMinGreaterThanEqualToMax {
            get {
                return ResourceManager.GetString("ExceptionLUTMinGreaterThanEqualToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot generate composite LUT because no LUTs have been added yet. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLUTNotAdded {
            get {
                return ResourceManager.GetString("ExceptionLUTNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Lut Preset is not applicable for the provided image. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLutPresetIsNotApplicableForTheProvidedImage {
            get {
                return ResourceManager.GetString("ExceptionLutPresetIsNotApplicableForTheProvidedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Window Centre value has been specified. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoWindowCenterHasBeenSpecified {
            get {
                return ResourceManager.GetString("ExceptionNoWindowCenterHasBeenSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Window Width value has been specified. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoWindowWidthHasBeenSpecified {
            get {
                return ResourceManager.GetString("ExceptionNoWindowWidthHasBeenSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified &apos;existing&apos; preset item is not in the collection. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPresetConfigurationDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionPresetConfigurationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Preset Name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPresetNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ExceptionPresetNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected keystroke must be one of the available keystrokes. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSelectedKeystrokeMustBeOneOfAvailable {
            get {
                return ResourceManager.GetString("ExceptionSelectedKeystrokeMustBeOneOfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property cannot be modified. 的本地化字符串。
        /// </summary>
        internal static string ExceptionThePropertyCannotBeModified {
            get {
                return ResourceManager.GetString("ExceptionThePropertyCannotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A valid synchronization context must exist on the current UI thread. 的本地化字符串。
        /// </summary>
        internal static string ExceptionValidSynchronizationContextMustExist {
            get {
                return ResourceManager.GetString("ExceptionValidSynchronizationContextMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Window Center value is invalid. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWindowCenterInvalid {
            get {
                return ResourceManager.GetString("ExceptionWindowCenterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The preset cannot be {0} because both its name and keystroke conflict with one or more existing presets.
        ///Please ensure that the name/keystroke combination is unique. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWindowLevelPresetDualConflict {
            get {
                return ResourceManager.GetString("ExceptionWindowLevelPresetDualConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The preset cannot be {0} because its {1} conflicts with one or more existing presets.
        ///Please ensure that the name/keystroke combination is unique. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWindowLevelPresetSingleConflict {
            get {
                return ResourceManager.GetString("ExceptionWindowLevelPresetSingleConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (Data) 的本地化字符串。
        /// </summary>
        internal static string FormatAutoVoiDataLutDescription {
            get {
                return ResourceManager.GetString("FormatAutoVoiDataLutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 x={0}, y={1} 的本地化字符串。
        /// </summary>
        internal static string FormatCoordinates {
            get {
                return ResourceManager.GetString("FormatCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W:{0:0.#} L:{1:0.#} ({2}) 的本地化字符串。
        /// </summary>
        internal static string FormatDescriptionAutoLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionAutoLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W:{0:0.#} L:{1:0.#} (Auto) 的本地化字符串。
        /// </summary>
        internal static string FormatDescriptionAutoLinearLutNoExplanation {
            get {
                return ResourceManager.GetString("FormatDescriptionAutoLinearLutNoExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W = {0}, L = {1} 的本地化字符串。
        /// </summary>
        internal static string FormatDescriptionLinearPreset {
            get {
                return ResourceManager.GetString("FormatDescriptionLinearPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W:{0} L:{1} ({2}) 的本地化字符串。
        /// </summary>
        internal static string FormatDescriptionPresetLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionPresetLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}x 的本地化字符串。
        /// </summary>
        internal static string FormatLabelZoomFixed {
            get {
                return ResourceManager.GetString("FormatLabelZoomFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string FormatLinearPresetDescription {
            get {
                return ResourceManager.GetString("FormatLinearPresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string FormatProbeInfo {
            get {
                return ResourceManager.GetString("FormatProbeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R={0}, G={1}, B={2} 的本地化字符串。
        /// </summary>
        internal static string FormatRGB {
            get {
                return ResourceManager.GetString("FormatRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (Reverse) 的本地化字符串。
        /// </summary>
        internal static string FormatSortByReverse {
            get {
                return ResourceManager.GetString("FormatSortByReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        internal static string FormatValueUnits {
            get {
                return ResourceManager.GetString("FormatValueUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified item already exists. 的本地化字符串。
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified item does not exist. 的本地化字符串。
        /// </summary>
        internal static string ItemDoesNotExist {
            get {
                return ResourceManager.GetString("ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keystroke 的本地化字符串。
        /// </summary>
        internal static string KeyStroke {
            get {
                return ResourceManager.GetString("KeyStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Text 的本地化字符串。
        /// </summary>
        internal static string LabelEnterText {
            get {
                return ResourceManager.GetString("LabelEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HU 的本地化字符串。
        /// </summary>
        internal static string LabelHounsfieldUnitsAbbreviation {
            get {
                return ResourceManager.GetString("LabelHounsfieldUnitsAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOC 的本地化字符串。
        /// </summary>
        internal static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAL 的本地化字符串。
        /// </summary>
        internal static string LabelModalityLut {
            get {
                return ResourceManager.GetString("LabelModalityLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (none) 的本地化字符串。
        /// </summary>
        internal static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n/a 的本地化字符串。
        /// </summary>
        internal static string LabelNotApplicable {
            get {
                return ResourceManager.GetString("LabelNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRES. STATE 的本地化字符串。
        /// </summary>
        internal static string LabelPresentationStateVoiDataLut {
            get {
                return ResourceManager.GetString("LabelPresentationStateVoiDataLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRES. STATE 的本地化字符串。
        /// </summary>
        internal static string LabelPresentationStateVoiLinearLut {
            get {
                return ResourceManager.GetString("LabelPresentationStateVoiLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAW 的本地化字符串。
        /// </summary>
        internal static string LabelRawPixel {
            get {
                return ResourceManager.GetString("LabelRawPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RGB 的本地化字符串。
        /// </summary>
        internal static string LabelRGBPixel {
            get {
                return ResourceManager.GetString("LabelRGBPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOI 的本地化字符串。
        /// </summary>
        internal static string LabelVOILut {
            get {
                return ResourceManager.GetString("LabelVOILut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to Tile 的本地化字符串。
        /// </summary>
        internal static string LabelZoomFit {
            get {
                return ResourceManager.GetString("LabelZoomFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear Window/Level Preset 的本地化字符串。
        /// </summary>
        internal static string LinearPresetVoiLutOperationFactoryDescription {
            get {
                return ResourceManager.GetString("LinearPresetVoiLutOperationFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cine 的本地化字符串。
        /// </summary>
        internal static string MenuCine {
            get {
                return ResourceManager.GetString("MenuCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Custom Shutters 的本地化字符串。
        /// </summary>
        internal static string MenuClearCustomShutters {
            get {
                return ResourceManager.GetString("MenuClearCustomShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Menu 的本地化字符串。
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Colour Bar 的本地化字符串。
        /// </summary>
        internal static string MenuColorBar {
            get {
                return ResourceManager.GetString("MenuColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Annotations 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteAllAnnotations {
            get {
                return ResourceManager.GetString("MenuDeleteAllAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteAnnotation {
            get {
                return ResourceManager.GetString("MenuDeleteAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter (Circle) 的本地化字符串。
        /// </summary>
        internal static string MenuDrawCircleShutter {
            get {
                return ResourceManager.GetString("MenuDrawCircleShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter (Polygon) 的本地化字符串。
        /// </summary>
        internal static string MenuDrawPolygonShutter {
            get {
                return ResourceManager.GetString("MenuDrawPolygonShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter (Rectangle) 的本地化字符串。
        /// </summary>
        internal static string MenuDrawRectangleShutter {
            get {
                return ResourceManager.GetString("MenuDrawRectangleShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter 的本地化字符串。
        /// </summary>
        internal static string MenuDrawShutter {
            get {
                return ResourceManager.GetString("MenuDrawShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip &amp;Horizontal 的本地化字符串。
        /// </summary>
        internal static string MenuFlipHorizontal {
            get {
                return ResourceManager.GetString("MenuFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip &amp;Vertical 的本地化字符串。
        /// </summary>
        internal static string MenuFlipVertical {
            get {
                return ResourceManager.GetString("MenuFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Properties 的本地化字符串。
        /// </summary>
        internal static string MenuImageProperties {
            get {
                return ResourceManager.GetString("MenuImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert 的本地化字符串。
        /// </summary>
        internal static string MenuInvert {
            get {
                return ResourceManager.GetString("MenuInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locate on Disk 的本地化字符串。
        /// </summary>
        internal static string MenuLocateOnDisk {
            get {
                return ResourceManager.GetString("MenuLocateOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W/L Presets 的本地化字符串。
        /// </summary>
        internal static string MenuLutPresets {
            get {
                return ResourceManager.GetString("MenuLutPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnification 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification {
            get {
                return ResourceManager.GetString("MenuMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5x 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification1AndOneHalf {
            get {
                return ResourceManager.GetString("MenuMagnification1AndOneHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2x 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification2x {
            get {
                return ResourceManager.GetString("MenuMagnification2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4x 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification4x {
            get {
                return ResourceManager.GetString("MenuMagnification4x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6x 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification6x {
            get {
                return ResourceManager.GetString("MenuMagnification6x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8x 的本地化字符串。
        /// </summary>
        internal static string MenuMagnification8x {
            get {
                return ResourceManager.GetString("MenuMagnification8x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Scale 的本地化字符串。
        /// </summary>
        internal static string MenuMatchScale {
            get {
                return ResourceManager.GetString("MenuMatchScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看内存 的本地化字符串。
        /// </summary>
        internal static string MenuMemoryUsage {
            get {
                return ResourceManager.GetString("MenuMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Pan 的本地化字符串。
        /// </summary>
        internal static string MenuPan {
            get {
                return ResourceManager.GetString("MenuPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Probe 的本地化字符串。
        /// </summary>
        internal static string MenuProbe {
            get {
                return ResourceManager.GetString("MenuProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R&amp;eset 的本地化字符串。
        /// </summary>
        internal static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate &amp;Left 的本地化字符串。
        /// </summary>
        internal static string MenuRotateLeft {
            get {
                return ResourceManager.GetString("MenuRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate &amp;Right 的本地化字符串。
        /// </summary>
        internal static string MenuRotateRight {
            get {
                return ResourceManager.GetString("MenuRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide &amp;Colour Bar 的本地化字符串。
        /// </summary>
        internal static string MenuShowHideColorBar {
            get {
                return ResourceManager.GetString("MenuShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        internal static string MenuShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Scale Overlay 的本地化字符串。
        /// </summary>
        internal static string MenuShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Shutter Overlay 的本地化字符串。
        /// </summary>
        internal static string MenuShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Text Overlay 的本地化字符串。
        /// </summary>
        internal static string MenuShowHideTextOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Raw Pixel Value 的本地化字符串。
        /// </summary>
        internal static string MenuShowRawPixelValue {
            get {
                return ResourceManager.GetString("MenuShowRawPixelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Post-VOI LUT Pixel Value 的本地化字符串。
        /// </summary>
        internal static string MenuShowVoiPixelValue {
            get {
                return ResourceManager.GetString("MenuShowVoiPixelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Stack 的本地化字符串。
        /// </summary>
        internal static string MenuStack {
            get {
                return ResourceManager.GetString("MenuStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常用工具 的本地化字符串。
        /// </summary>
        internal static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add &amp;Text 的本地化字符串。
        /// </summary>
        internal static string MenuTextArea {
            get {
                return ResourceManager.GetString("MenuTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Text &amp;Callout 的本地化字符串。
        /// </summary>
        internal static string MenuTextCallout {
            get {
                return ResourceManager.GetString("MenuTextCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Window/Level 的本地化字符串。
        /// </summary>
        internal static string MenuWindowLevel {
            get {
                return ResourceManager.GetString("MenuWindowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (List of Window/Level Presets) 的本地化字符串。
        /// </summary>
        internal static string MenuWindowLevelPresetList {
            get {
                return ResourceManager.GetString("MenuWindowLevelPresetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level Presets 的本地化字符串。
        /// </summary>
        internal static string MenuWindowLevelPresets {
            get {
                return ResourceManager.GetString("MenuWindowLevelPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Zoom 的本地化字符串。
        /// </summary>
        internal static string MenuZoom {
            get {
                return ResourceManager.GetString("MenuZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;1X 的本地化字符串。
        /// </summary>
        internal static string MenuZoom1X {
            get {
                return ResourceManager.GetString("MenuZoom1X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;2X 的本地化字符串。
        /// </summary>
        internal static string MenuZoom2X {
            get {
                return ResourceManager.GetString("MenuZoom2X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;4X 的本地化字符串。
        /// </summary>
        internal static string MenuZoom4X {
            get {
                return ResourceManager.GetString("MenuZoom4X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add the specified preset. 的本地化字符串。
        /// </summary>
        internal static string MessageFailedToAddPreset {
            get {
                return ResourceManager.GetString("MessageFailedToAddPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to edit the specified preset. 的本地化字符串。
        /// </summary>
        internal static string MessageFailedToEditPreset {
            get {
                return ResourceManager.GetString("MessageFailedToEditPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save Window/Level Preset changes. 的本地化字符串。
        /// </summary>
        internal static string MessageFailedToSaveWindowLevelPresetChanges {
            get {
                return ResourceManager.GetString("MessageFailedToSaveWindowLevelPresetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The factory object ({0}) does not implement interface &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatFactoryDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("MessageFormatFactoryDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The factory object ({0}) does not specify a name. 的本地化字符串。
        /// </summary>
        internal static string MessageFormatFactoryHasNoName {
            get {
                return ResourceManager.GetString("MessageFormatFactoryHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name and/or keystroke entered conflicts with at least one other existing preset. 的本地化字符串。
        /// </summary>
        internal static string MessageNameOrKeystrokeConflictsWithExistingPreset {
            get {
                return ResourceManager.GetString("MessageNameOrKeystrokeConflictsWithExistingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is not enough of the selected image visible to match the scale. 的本地化字符串。
        /// </summary>
        internal static string MessageNotEnoughImageVisible {
            get {
                return ResourceManager.GetString("MessageNotEnoughImageVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select an item to delete. 的本地化字符串。
        /// </summary>
        internal static string MessagePleaseSelectAnItemToDelete {
            get {
                return ResourceManager.GetString("MessagePleaseSelectAnItemToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select an item to edit. 的本地化字符串。
        /// </summary>
        internal static string MessagePleaseSelectAnItemToEdit {
            get {
                return ResourceManager.GetString("MessagePleaseSelectAnItemToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occurred while probing the image.
        ///Please check the log for more details. 的本地化字符串。
        /// </summary>
        internal static string MessageProbeToolError {
            get {
                return ResourceManager.GetString("MessageProbeToolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The shutter area is too small. 的本地化字符串。
        /// </summary>
        internal static string MessageShutterTooSmall {
            get {
                return ResourceManager.GetString("MessageShutterTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected image is not stored on your local file system. 的本地化字符串。
        /// </summary>
        internal static string MessageUnableToLocateNonLocalImage {
            get {
                return ResourceManager.GetString("MessageUnableToLocateNonLocalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculates Window/Level from the minimum and maximum pixel values 的本地化字符串。
        /// </summary>
        internal static string MinMaxAlgorithmPresetVoiLutOperationComponentDescription {
            get {
                return ResourceManager.GetString("MinMaxAlgorithmPresetVoiLutOperationComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min/Max Algorithm 的本地化字符串。
        /// </summary>
        internal static string MinMaxAlgorithmPresetVoiLutOperationComponentName {
            get {
                return ResourceManager.GetString("MinMaxAlgorithmPresetVoiLutOperationComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min/Max Algorithm 的本地化字符串。
        /// </summary>
        internal static string MinMaxAlgorithmPresetVoiLutOperationFactoryDescription {
            get {
                return ResourceManager.GetString("MinMaxAlgorithmPresetVoiLutOperationFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LUT 的本地化字符串。
        /// </summary>
        internal static string PrefixDefaultVoiDataLutExplanation {
            get {
                return ResourceManager.GetString("PrefixDefaultVoiDataLutExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition Time 的本地化字符串。
        /// </summary>
        internal static string SortByAcquisitionTimeDescription {
            get {
                return ResourceManager.GetString("SortByAcquisitionTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Number 的本地化字符串。
        /// </summary>
        internal static string SortByImageNumberDescription {
            get {
                return ResourceManager.GetString("SortByImageNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slice Location 的本地化字符串。
        /// </summary>
        internal static string SortBySliceLocationDescription {
            get {
                return ResourceManager.GetString("SortBySliceLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Tools 的本地化字符串。
        /// </summary>
        internal static string StandardTools {
            get {
                return ResourceManager.GetString("StandardTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Preset 的本地化字符串。
        /// </summary>
        internal static string TitleAddPreset {
            get {
                return ResourceManager.GetString("TitleAddPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Window/Level Preset 的本地化字符串。
        /// </summary>
        internal static string TitleAddWindowLevelPreset {
            get {
                return ResourceManager.GetString("TitleAddWindowLevelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cine 的本地化字符串。
        /// </summary>
        internal static string TitleCine {
            get {
                return ResourceManager.GetString("TitleCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Preset 的本地化字符串。
        /// </summary>
        internal static string TitleEditPreset {
            get {
                return ResourceManager.GetString("TitleEditPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Window/Level Preset 的本地化字符串。
        /// </summary>
        internal static string TitleEditWindowLevelPreset {
            get {
                return ResourceManager.GetString("TitleEditWindowLevelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        internal static string TitleKey {
            get {
                return ResourceManager.GetString("TitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string TitleTools {
            get {
                return ResourceManager.GetString("TitleTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level 的本地化字符串。
        /// </summary>
        internal static string TitleWindowLevel {
            get {
                return ResourceManager.GetString("TitleWindowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cine 的本地化字符串。
        /// </summary>
        internal static string ToolbarCine {
            get {
                return ResourceManager.GetString("ToolbarCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Custom Shutters 的本地化字符串。
        /// </summary>
        internal static string ToolbarClearCustomShutters {
            get {
                return ResourceManager.GetString("ToolbarClearCustomShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colour Bar 的本地化字符串。
        /// </summary>
        internal static string ToolbarColorBar {
            get {
                return ResourceManager.GetString("ToolbarColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Annotations 的本地化字符串。
        /// </summary>
        internal static string ToolbarDeleteAllAnnotations {
            get {
                return ResourceManager.GetString("ToolbarDeleteAllAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        internal static string ToolbarDicomOverlay {
            get {
                return ResourceManager.GetString("ToolbarDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter 的本地化字符串。
        /// </summary>
        internal static string ToolbarDrawShutter {
            get {
                return ResourceManager.GetString("ToolbarDrawShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Horizontal 的本地化字符串。
        /// </summary>
        internal static string ToolbarFlipHorizontal {
            get {
                return ResourceManager.GetString("ToolbarFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Vertical 的本地化字符串。
        /// </summary>
        internal static string ToolbarFlipVertical {
            get {
                return ResourceManager.GetString("ToolbarFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Properties 的本地化字符串。
        /// </summary>
        internal static string ToolbarImageProperties {
            get {
                return ResourceManager.GetString("ToolbarImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert 的本地化字符串。
        /// </summary>
        internal static string ToolbarInvert {
            get {
                return ResourceManager.GetString("ToolbarInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnification 的本地化字符串。
        /// </summary>
        internal static string ToolbarMagnification {
            get {
                return ResourceManager.GetString("ToolbarMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Scale 的本地化字符串。
        /// </summary>
        internal static string ToolbarMatchScale {
            get {
                return ResourceManager.GetString("ToolbarMatchScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        internal static string ToolbarPan {
            get {
                return ResourceManager.GetString("ToolbarPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Probe 的本地化字符串。
        /// </summary>
        internal static string ToolbarProbe {
            get {
                return ResourceManager.GetString("ToolbarProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string ToolbarRedo {
            get {
                return ResourceManager.GetString("ToolbarRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string ToolbarReset {
            get {
                return ResourceManager.GetString("ToolbarReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Counterclockwise 90 Degrees 的本地化字符串。
        /// </summary>
        internal static string ToolbarRotateLeft {
            get {
                return ResourceManager.GetString("ToolbarRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Clockwise 90 Degrees 的本地化字符串。
        /// </summary>
        internal static string ToolbarRotateRight {
            get {
                return ResourceManager.GetString("ToolbarRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Overlay 的本地化字符串。
        /// </summary>
        internal static string ToolbarScaleOverlay {
            get {
                return ResourceManager.GetString("ToolbarScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Overlays 的本地化字符串。
        /// </summary>
        internal static string ToolbarShowHideOverlays {
            get {
                return ResourceManager.GetString("ToolbarShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutter Overlay 的本地化字符串。
        /// </summary>
        internal static string ToolbarShutterOverlay {
            get {
                return ResourceManager.GetString("ToolbarShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack 的本地化字符串。
        /// </summary>
        internal static string ToolbarStack {
            get {
                return ResourceManager.GetString("ToolbarStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Text Area 的本地化字符串。
        /// </summary>
        internal static string ToolbarTextArea {
            get {
                return ResourceManager.GetString("ToolbarTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Text Callout 的本地化字符串。
        /// </summary>
        internal static string ToolbarTextCallout {
            get {
                return ResourceManager.GetString("ToolbarTextCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Overlay 的本地化字符串。
        /// </summary>
        internal static string ToolbarTextOverlay {
            get {
                return ResourceManager.GetString("ToolbarTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string ToolbarUndo {
            get {
                return ResourceManager.GetString("ToolbarUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level 的本地化字符串。
        /// </summary>
        internal static string ToolbarWindowLevel {
            get {
                return ResourceManager.GetString("ToolbarWindowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string ToolbarZoom {
            get {
                return ResourceManager.GetString("ToolbarZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W/L Presets 的本地化字符串。
        /// </summary>
        internal static string ToolsPresets {
            get {
                return ResourceManager.GetString("ToolsPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cine 的本地化字符串。
        /// </summary>
        internal static string TooltipCine {
            get {
                return ResourceManager.GetString("TooltipCine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Custom Shutters 的本地化字符串。
        /// </summary>
        internal static string TooltipClearCustomShutters {
            get {
                return ResourceManager.GetString("TooltipClearCustomShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colour Bar 的本地化字符串。
        /// </summary>
        internal static string TooltipColorBar {
            get {
                return ResourceManager.GetString("TooltipColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Annotations 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteAllAnnotations {
            get {
                return ResourceManager.GetString("TooltipDeleteAllAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        internal static string TooltipDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Shutter 的本地化字符串。
        /// </summary>
        internal static string TooltipDrawShutter {
            get {
                return ResourceManager.GetString("TooltipDrawShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Horizontal 的本地化字符串。
        /// </summary>
        internal static string TooltipFlipHorizontal {
            get {
                return ResourceManager.GetString("TooltipFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Vertical 的本地化字符串。
        /// </summary>
        internal static string TooltipFlipVertical {
            get {
                return ResourceManager.GetString("TooltipFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Properties 的本地化字符串。
        /// </summary>
        internal static string TooltipImageProperties {
            get {
                return ResourceManager.GetString("TooltipImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert 的本地化字符串。
        /// </summary>
        internal static string TooltipInvert {
            get {
                return ResourceManager.GetString("TooltipInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locates the selected image(s) on disk 的本地化字符串。
        /// </summary>
        internal static string TooltipLocateOnDisk {
            get {
                return ResourceManager.GetString("TooltipLocateOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnification 的本地化字符串。
        /// </summary>
        internal static string TooltipMagnification {
            get {
                return ResourceManager.GetString("TooltipMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Scale 的本地化字符串。
        /// </summary>
        internal static string TooltipMatchScale {
            get {
                return ResourceManager.GetString("TooltipMatchScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        internal static string TooltipPan {
            get {
                return ResourceManager.GetString("TooltipPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Probe 的本地化字符串。
        /// </summary>
        internal static string TooltipProbe {
            get {
                return ResourceManager.GetString("TooltipProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string TooltipRedo {
            get {
                return ResourceManager.GetString("TooltipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string TooltipReset {
            get {
                return ResourceManager.GetString("TooltipReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Counterclockwise 90 Degrees 的本地化字符串。
        /// </summary>
        internal static string TooltipRotateLeft {
            get {
                return ResourceManager.GetString("TooltipRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate Clockwise 90 Degrees 的本地化字符串。
        /// </summary>
        internal static string TooltipRotateRight {
            get {
                return ResourceManager.GetString("TooltipRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Overlay 的本地化字符串。
        /// </summary>
        internal static string TooltipScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Colour Bar 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideColorBar {
            get {
                return ResourceManager.GetString("TooltipShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide DICOM Overlay(s) 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Overlays 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideOverlays {
            get {
                return ResourceManager.GetString("TooltipShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Scale Overlay 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Shutter Overlay 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Text Overlay 的本地化字符串。
        /// </summary>
        internal static string TooltipShowHideTextOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack 的本地化字符串。
        /// </summary>
        internal static string TooltipStack {
            get {
                return ResourceManager.GetString("TooltipStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Area 的本地化字符串。
        /// </summary>
        internal static string TooltipTextArea {
            get {
                return ResourceManager.GetString("TooltipTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Callout 的本地化字符串。
        /// </summary>
        internal static string TooltipTextCallout {
            get {
                return ResourceManager.GetString("TooltipTextCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Overlay 的本地化字符串。
        /// </summary>
        internal static string TooltipTextOverlay {
            get {
                return ResourceManager.GetString("TooltipTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string TooltipUndo {
            get {
                return ResourceManager.GetString("TooltipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window/Level 的本地化字符串。
        /// </summary>
        internal static string TooltipWindowLevel {
            get {
                return ResourceManager.GetString("TooltipWindowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string TooltipZoom {
            get {
                return ResourceManager.GetString("TooltipZoom", resourceCulture);
            }
        }
    }
}
