//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.Desktop {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class LocalePolicy : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalePolicy defaultInstance = ((LocalePolicy)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalePolicy())));
        
        public static LocalePolicy Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Comma-separated list of culture codes allowed for use
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Comma-separated list of culture codes allowed for use")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllowedLocalizationsList {
            get {
                return ((string)(this["AllowedLocalizationsList"]));
            }
        }
    }
}
